### ISSUE TITLE
NullPointerException for ActivityButtonsImpl

### ISSUE THREAD

**Issue by montlikadani** [Javacord/Javacord#1010]
```
2022-06-05 16:21:28.915+0200 WARN org.javacord.core.util.gateway.PacketHandler Couldn't handle packet of type GUILD_CREATE. Please contact the developer!
 java.lang.NullPointerException: Cannot invoke "com.fasterxml.jackson.databind.JsonNode.asText()" because the return value of "com.fasterxml.jackson.databind.JsonNode.get(String)" is null
	at org.javacord.core.entity.activity.ActivityButtonsImpl.<init>(ActivityButtonsImpl.java:18)
	at org.javacord.core.entity.activity.ActivityImpl.<init>(ActivityImpl.java:94)
	at org.javacord.core.entity.server.ServerImpl.<init>(ServerImpl.java:467)
	at org.javacord.core.util.handler.guild.GuildCreateHandler.handle(GuildCreateHandler.java:33)
	at org.javacord.core.util.gateway.PacketHandler.lambda$handlePacket$0(PacketHandler.java:51)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```
_I had to remove the packet response from Exception message as the comment is too long_

According to the [Discord Docs](https://discord.com/developers/docs/topics/gateway#activity-object-activity-buttons) about activity button these two field can not return null, but somehow for me it throws this exception.

I have these connection parameters specified for connecting to DiscordApi:
```java
new DiscordApiBuilder().setToken("hidden").setAllIntents()
    .setWaitForUsersOnStartup(true).setShutdownHookRegistrationEnabled(false)
    .setWaitForServersOnStartup(true).login().thenAccept(a -> {
  // My impls here
});
```

I created a simple diff to mark what to be changed.
`ActivityButtonsImpl.java`
```diff
    public ActivityButtonsImpl(JsonNode data) {
-
-       this.label = data.get("label").asText();
+       this.label = data.has("label") ? data.get("label").asText() : null;
-
-       this.url = data.get("url").asText();
+       this.url = data.has("url") ? data.get("url").asText() : null;
    }

    @Override
-   public String getLabel() {
+   public Optional<String> getLabel() {
-       return label;
+       return Optional.ofNullable(label);
    }

    @Override
-   public String getUrl() {
+   public Optional<String> getUrl() {
-      return url;
+      return Optional.ofNullable(url);
    }
}
```
`ActivityButtons.java`
```diff
+ import java.util.Optional;
+
public interface ActivityButtons {
    /**
-     * Gets the text shown on the button.
+     * Gets the text shown on the button if present.
     *
-     * @return The text shown on the button.
+     * @return The text shown on the button if present.
     */
-    String getLabel();
+    Optional<String> getLabel();

    /**
-     * The url which is opened when the button is clicked.
+     * The url which is opened when the button is clicked or {@link Optional#empty()} if not present.
     *
-     * @return The url which is opened when the button is clicked.
+     * @return The url which is opened when the button is clicked or {@link Optional#empty()} if not present.
     */
-    String getUrl();
+    Optional<String> getUrl();
```

**Comment by KILLEliteMaste** [comment]
Can you please also send the JSON packet or more specific the buttons JSON?
The documentation states
> When received over the gateway, the buttons field is an array of strings, which are the button labels

Which would mean that it should look something like `buttons: ["one","two"]`. In that case the documentation is quiet misleading and they should highlight the text

**Comment by montlikadani** [comment]
https://pastebin.com/PuAbWFBG

**Comment by KILLEliteMaste** [comment]
Are you sure this is the correct JSON? It doesn't contain any `buttons` structure

**Comment by montlikadani** [comment]
> Are you sure this is the correct JSON? It doesn't contain any `buttons` structure

Yep, this is what the exception throws.

**Comment by montlikadani** [comment]
This exception is thrown when:
- the applications starts and the process attempts a login to discordApi
- Discord pushes a "restart" to api
- 
I have some buttons created like `SelectMenuOption` and a simple Button added as a component to a message. These button components have been around for over 1 month, have not been modified since, and have not had this problem so far.

**Comment by KILLEliteMaste** [comment]
Buttons != ActivityButtons. The Buttons are the components you are talking about but the latter is about the users activity which can contains buttons. I think they appear for example when you listen to Spotify and then can join the session. The error really can't appear unless the JSON contains the buttons for the users activity.

**Comment by montlikadani** [comment]
I thought ActivityButton implements Button, but I realized it is not the same. I copied a new exception that contains a user activity, I think this user listening to Youtube Music (or changed now): https://pastebin.com/PvMdaNbU

**Comment by KILLEliteMaste** [comment]
Yeah, like I expected this only has an array with some string. Going to do a PR which addresses this issue
