### ISSUE TITLE
NullPointerException thrown when loading messages in MessageImpl

### ISSUE THREAD

**Issue by montlikadani** [Javacord/Javacord#1129]
[This commit](https://github.com/Javacord/Javacord/commit/851989cb7ebc71a2556bb88662c44b2d0faa712c) introduced message position and this `position` may return null according to discord docs. The field `position` uses the Integer wrapper of `int` which is the correct way to handle nulls, but the [private constructor of MessageImpl](https://github.com/Javacord/Javacord/commit/851989cb7ebc71a2556bb88662c44b2d0faa712c#diff-ac4f0b46ded65a331a11108b3680994c8a9c9c096a4dafbb8d046d95b7a88059R260) contains the primitive type of `position` which causes this exception on startup.

```
 java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because "this.position" is null
	at org.javacord.core.entity.message.MessageImpl.copyMessage(MessageImpl.java:294)
	at java.base/java.util.Optional.map(Optional.java:260)
	at org.javacord.core.util.handler.message.MessageUpdateHandler.handle(MessageUpdateHandler.java:81)
	at org.javacord.core.util.gateway.PacketHandler.lambda$handlePacket$0(PacketHandler.java:51)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
```

This parameter type should be changed to `Integer` wrapper for allowing null values.

**Comment by RealYusufIsmail** [comment]
Will have a look at this, tomorrow
