### ISSUE TITLE
 [org.javacord.core.util.gateway.DiscordWebSocketAdapter] Websocket callback error!

### ISSUE THREAD

**Issue by imyoric** [Javacord/Javacord#1142]
### Javacord version

3.5.0

### Steps to reproduce

I disconnect from server by: api.disconnect()

### What is expected?

A quiet shutdown without errors is expected

### What is actually happening?

```
[12:06:07 ERROR]: [org.javacord.core.util.gateway.DiscordWebSocketAdapter] Websocket callback error!
java.lang.IllegalStateException: zip file closed
	at java.util.zip.ZipFile.ensureOpen(ZipFile.java:831) ~[?:?]
	at java.util.zip.ZipFile.getEntry(ZipFile.java:330) ~[?:?]
	at java.util.jar.JarFile.getEntry(JarFile.java:518) ~[?:?]
	at java.util.jar.JarFile.getJarEntry(JarFile.java:473) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:189) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:129) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:124) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at org.javacord.core.util.gateway.DiscordWebSocketAdapter.onDisconnected(DiscordWebSocketAdapter.java:508) ~[SecretPlugin-1.0-198.jar:?]
	at com.neovisionaries.ws.client.ListenerManager.callOnDisconnected(ListenerManager.java:224) ~[SecretPlugin-1.0-198.jar:?]
	at com.neovisionaries.ws.client.WebSocket.finish(WebSocket.java:3758) ~[SecretPlugin-1.0-198.jar:?]
	at com.neovisionaries.ws.client.WebSocket.onThreadsFinished(WebSocket.java:3724) ~[SecretPlugin-1.0-198.jar:?]
	at com.neovisionaries.ws.client.WebSocket.onReadingThreadFinished(WebSocket.java:3691) ~[SecretPlugin-1.0-198.jar:?]
	at com.neovisionaries.ws.client.ReadingThread.notifyFinished(ReadingThread.java:1138) ~[SecretPlugin-1.0-198.jar:?]
	at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:80) ~[SecretPlugin-1.0-198.jar:?]
	at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45) ~[SecretPlugin-1.0-198.jar:?]
```

**Comment by Vampire** [comment]
You let Bukkit close the class loader and thus the underlying zip of your plugin but during the orderly shutdown a new class is neede wich then cannot be found.
Wait for the shutdown to finish, by `join`ing on the `CompletableFuture` you are getting back from the `disconnect` call.

**Comment by imyoric** [comment]
thanks
