### ISSUE TITLE
Couldn't handle packet of type INTERACTION_CREATE in a "text in voice channel" scenario 

### ISSUE THREAD

**Issue by journeyman88** [Javacord/Javacord#1198]
### Javacord version

3.7.0

### Steps to reproduce

1. Register a global SlashCommand in the bot
2. Open a VoiceChannel in Discord
3. Open the TextChannel
4. Invoke the SlashCommand

### What is expected?

The command should return its result.

### What is actually happening?

The command do not respond. 

In the bot log the following log is found (I've removed the packet from the log (aside the version and type fields))
`WARN  org.javacord.core.util.gateway.PacketHandler - Couldn't handle packet of type INTERACTION_CREATE. Please contact the developer! (packet: {"version":1,"type":2, ...})
java.lang.AssertionError: null
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at org.javacord.core.interaction.InteractionImpl.<init>(InteractionImpl.java:80) ~[javacord-core-3.7.0.jar:?]
	at org.javacord.core.interaction.ApplicationCommandInteractionImpl.<init>(ApplicationCommandInteractionImpl.java:25) ~[javacord-core-3.7.0.jar:?]
	at org.javacord.core.interaction.SlashCommandInteractionImpl.<init>(SlashCommandInteractionImpl.java:33) ~[javacord-core-3.7.0.jar:?]
	at org.javacord.core.util.handler.interaction.InteractionCreateHandler.handle(InteractionCreateHandler.java:86) ~[javacord-core-3.7.0.jar:?]
	at org.javacord.core.util.gateway.PacketHandler.lambda$handlePacket$0(PacketHandler.java:51) ~[javacord-core-3.7.0.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]`

**Comment by Vampire** [comment]
This will hopefully be fixed with #1014
