### ISSUE TITLE
NumberFormatException: For input string: (some floating point number)

### ISSUE THREAD

**Issue by tfes8** [Javacord/Javacord#1199]
### Javacord version

3.1.2

### Steps to reproduce

I'm getting a weird error and I'm unsure how to reproduce it.  Occasionally on my app the RateLimitManager flips out and floods my logs with:
```
java.lang.NumberFormatException: For input string: "1671650785.500"
        at java.base/java.lang.NumberFormatException.forInputString(Unknown Source) ~[na:na]
        at java.base/java.lang.Long.parseLong(Unknown Source) ~[na:na]
        at java.base/java.lang.Long.parseLong(Unknown Source) ~[na:na]
        at org.javacord.core.util.ratelimit.RatelimitManager.lambda$handleResponse$4(RatelimitManager.java:181) ~[javacord-core-3.1.2.jar!/:na]
        at java.base/java.util.Optional.orElseGet(Unknown Source) ~[na:na]
        at org.javacord.core.util.ratelimit.RatelimitManager.handleResponse(RatelimitManager.java:181) ~[javacord-core-3.1.2.jar!/:na]
        at org.javacord.core.util.ratelimit.RatelimitManager.lambda$queueRequest$2(RatelimitManager.java:138) ~[javacord-core-3.1.2.jar!/:na]
```

I tried tracking it down, but since its originating from a ThreadPool, i'm not sure what's cause it because the original exception is hidden.

### What is expected?

See above

### What is actually happening?

A repeating exception multiple times per second that floods the logs.

**Comment by Mysterypotatoguy** [comment]
Version 3.1.2 is over two years old at this point. You should consider upgrading as Javacord (and Discord) have made some changes to the ratelimit API in the time between

**Comment by Saladoc** [comment]
Closing this. As Mysterypotatoguy said, the version you're using is positively ancient. Please update to a current release. Past releases are not supported since they often are incompatible with discords ever changing api.
