### ISSUE TITLE
Slash command in Voice Channel text fails, couldn't handle packet of type INTERACTION_CREATE

### ISSUE THREAD

**Issue by Willdotwhite** [Javacord/Javacord#1212]
### Javacord version

3.7.0

### Steps to reproduce

1: Create a slash command which can be called by any user in a server (e.g. a global `/ping` command)
2: Join a voice channel and open the chat for this voice channel
3: Run slash command

### What is expected?

The slash command resolves correctly and responds into the VC chat

### What is actually happening?

```
2023-02-10 10:55:07.001+0000 WARN org.javacord.core.util.gateway.PacketHandler Couldn't handle packet of type INTERACTION_CREATE. Please contact the developer! (packet: {"version":1,"type":2,"token":"REDACTED","member":{"user":{"username":"Dotwo (he/him)","public_flags":0,"id":"427486675409829898","display_name":null,"discriminator":"5394","avatar_decoration":null,"avatar":"b7d1e62d7b31afe2fbf7fc4e36e0891e"},"roles":["1070469421333741698","1073543084920537198"],"premium_since":null,"permissions":"4398046511103","pending":false,"nick":null,"mute":false,"joined_at":"2023-01-27T13:09:33.870000+00:00","is_pending":false,"flags":0,"deaf":false,"communication_disabled_until":null,"avatar":null},"locale":"en-GB","id":"1073557722928267365","guild_locale":"en-US","guild_id":"1068518127970824253","entitlement_sku_ids":[],"data":{"type":1,"name":"ping","id":"1068525231074983966"},"channel_id":"1073555810053017700","application_id":"1068523922137563136","app_permissions":"4398046511103"}) {shard=0} 
 java.lang.AssertionError
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at org.javacord.core.interaction.InteractionImpl.<init>(InteractionImpl.java:80)
	at org.javacord.core.interaction.ApplicationCommandInteractionImpl.<init>(ApplicationCommandInteractionImpl.java:25)
	at org.javacord.core.interaction.SlashCommandInteractionImpl.<init>(SlashCommandInteractionImpl.java:33)
	at org.javacord.core.util.handler.interaction.InteractionCreateHandler.handle(InteractionCreateHandler.java:86)
	at org.javacord.core.util.gateway.PacketHandler.lambda$handlePacket$0(PacketHandler.java:51)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

### Any additional comments?

Could be related to https://github.com/Javacord/Javacord/issues/795 ?

**Comment by Willdotwhite** [comment]
Tested on `3.8.0-SNAPSHOT`, works as expected 👍

**Comment by Willdotwhite** [comment]
Proof of difference between `3.7.0` and `3.8.0-SNAPSHOT`
<img width="317" alt="image" src="https://user-images.githubusercontent.com/13312237/218080147-dc9b37ff-4697-4d71-9679-0e6e87c21a61.png">
