### ISSUE TITLE
Wrong channel type after an ephemeral response

### ISSUE THREAD

**Issue by Rapha149** [Javacord/Javacord#1304]
### Javacord version

3.8.0

### Steps to reproduce

1. Set up a slash command
2. Respond to the slash command interaction with an ephemeral message
3. Any incoming message and application command events for that channel are now failing

### What is expected?

That Javacord handles the incoming events for that channel correctly after the execution of that slash command.

### What is actually happening?

So it took me a while of debugging to figure this out, but here's what's happening:
Apparently, when you respond to a slash command executed in a voice channel with an ephemeral message, the cached channel is changed from a `ServerVoiceChannel` to a `PrivateChannel`. I have absolutely no idea why and I'm not familiar enough with Javacord to figure that out.

But I know this to be true because I debugged the `MessageCreateHandler#handle` method and after responding with an ephemeral message the api call `DiscordApiImpl#getTextChannelById` returns a `PrivateChannel` instead of a `ServerVoiceChannel` from the cache. This is a problem because Javacord uses `MessageImpl#getServer` in `MessageAuthorImpl` on line 55. `MessageImpl#getServer` returns the server from the underlying channel but since that's now a private channel there is no server to return and I get an error (see next question).
When I removed the channel cache after the responding using `DiscordApiImpl#removeChannelFromCache` the incoming messages and application commands were handled correctly again.

I would try to fix this issue myself using a pull request but unfortunately, as I said, I have no idea why the channel cache get's changed after an ephemeral response. This is also not the case for normal server text channels, only for voice channels. It's also not the case for non-ephemeral responses. My short-term solution for this is to just remove the channel cache every time but that just doesn't seem practical in the long run.

### Any additional comments?

This is the error I get when Javacord tries to handle an incoming message:
```
2024-05-12 13:54:17 [Javacord - Handlers Processor] WARN org.javacord.core.util.gateway.PacketHandler - Couldn't handle packet of type MESSAGE_CREATE. Please contact the developer! (packet: {"type":0,"tts":false,"timestamp":"2024-05-12T11:54:17.349000+00:00","referenced_message":null,"pinned":false,"nonce":"1239183868418850816","mentions":[],"mention_roles":[],"mention_everyone":false,"member":{"roles":["743565794872393829","743565805723058278","749271171400204392","743565802556489899","743565809334616175","743565808570990703","749271213645496400"],"premium_since":null,"pending":false,"nick":null,"mute":false,"joined_at":"2020-08-13T20:20:24.080000+00:00","flags":4,"deaf":false,"communication_disabled_until":null,"avatar":null},"id":"1239183869236871178","flags":0,"embeds":[],"edited_timestamp":null,"content":"test","components":[],"channel_id":"1182416461277450291","author":{"username":"rapha149","public_flags":4194432,"id":"530450131179405344","global_name":"Rapha","discriminator":"0","clan":null,"avatar_decoration_data":null,"avatar":"01d1772c0afa2da088cfc0741abf6de0"},"attachments":[],"guild_id":"743564541664690290"})
java.lang.AssertionError: null
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at org.javacord.core.entity.message.MessageAuthorImpl.<init>(MessageAuthorImpl.java:55) ~[javacord-core-3.8.0.jar:?]
	at org.javacord.core.entity.message.MessageImpl.<init>(MessageImpl.java:197) ~[javacord-core-3.8.0.jar:?]
	at org.javacord.core.DiscordApiImpl.lambda$getOrCreateMessage$33(DiscordApiImpl.java:1184) ~[javacord-core-3.8.0.jar:?]
	at java.util.Optional.orElseGet(Optional.java:364) ~[?:?]
	at org.javacord.core.DiscordApiImpl.getOrCreateMessage(DiscordApiImpl.java:1184) ~[javacord-core-3.8.0.jar:?]
	at org.javacord.core.util.handler.message.MessageCreateHandler.handle(MessageCreateHandler.java:90) ~[javacord-core-3.8.0.jar:?]
	at org.javacord.core.util.handler.message.MessageCreateHandler.handle(MessageCreateHandler.java:83) ~[javacord-core-3.8.0.jar:?]
	at org.javacord.core.util.gateway.PacketHandler.lambda$handlePacket$0(PacketHandler.java:51) ~[javacord-core-3.8.0.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by Rapha149** [comment]
Ok, after I tested it some more I came to the conclusion that the problem was not with deleting messages but with the ephemeral responses and then I checked for issues for the same problem again and I found this pull request: #1251 which seems to fix this problem.
