### ISSUE TITLE
Received channel update event for unknown role

### ISSUE THREAD

**Issue by Bastian** [Javacord/Javacord#438]
```
2019-02-16 23:56:25.786  WARN 27255 --- [dlers Processor] o.j.core.util.gateway.PacketHandler      : Couldn't handle packet of type CHANNEL_UPDATE. Please contact the developer! (packet: {"user_limit":0,"type":2,"position":0,"permission_overwrites":[{"type":"role","id":"411246417714216960","deny":1048576,"allow":1024},{"type":"role","id":"531076405904015361","deny":2097152,"allow":0}],"parent_id":null,"nsfw":false,"name":"User Count: 163707","id":"531175496881537024","guild_id":"411246417714216960","bitrate":64000})

java.lang.IllegalStateException: Received channel update event with unknown role!
        at org.javacord.core.util.handler.channel.ChannelUpdateHandler.lambda$handleServerChannel$0(ChannelUpdateHandler.java:143) ~[javacord-3.0.3.jar!/:na]
        at java.base/java.util.Optional.orElseThrow(Optional.java:408) ~[na:na]
        at org.javacord.core.util.handler.channel.ChannelUpdateHandler.lambda$handleServerChannel$4(ChannelUpdateHandler.java:142) ~[javacord-3.0.3.jar!/:na]
        at java.base/java.util.Optional.ifPresent(Optional.java:183) ~[na:na]
        at org.javacord.core.util.handler.channel.ChannelUpdateHandler.handleServerChannel(ChannelUpdateHandler.java:97) ~[javacord-3.0.3.jar!/:na]
        at org.javacord.core.util.handler.channel.ChannelUpdateHandler.handle(ChannelUpdateHandler.java:74) ~[javacord-3.0.3.jar!/:na]
        at org.javacord.core.util.gateway.PacketHandler.lambda$handlePacket$0(PacketHandler.java:52) ~[javacord-3.0.3.jar!/:na]
[...]
```

**Comment by coaxial1** [comment]
Here's another one:

```
> 2019-02-17 01:11:24.662  WARN 27255 --- [dlers Processor] o.j.core.util.gateway.PacketHandler      : Couldn't handle packet of type CHANNEL_DELETE. Please contact the developer! (packet: {"user_limit":2,"type":2,"position":10,"permission_overwrites":[],"parent_id":"528369918241013811","nsfw":false,"name":"║Fortnite - Duo [smply | SmileX]","id":"546483632252911648","guild_id":"528368817924079617","bitrate":64000})
> 
> java.lang.ClassCastException: class org.javacord.core.entity.channel.ServerVoiceChannelImpl cannot be cast to class org.javacord.core.util.Cleanupable (org.javacord.core.entity.channel.ServerVoiceChannelImpl and org.javacord.core.util.Cleanupable are in unnamed module of loader org.springframework.boot.loader.LaunchedURLClassLoader @61df66b6)
>         at org.javacord.core.DiscordApiImpl.lambda$removeChannelFromCache$15(DiscordApiImpl.java:680) ~[javacord-3.0.3.jar!/:na]
>         at java.base/java.util.concurrent.ConcurrentHashMap.computeIfPresent(ConcurrentHashMap.java:1822) ~[na:na]
>         at org.javacord.core.DiscordApiImpl.removeChannelFromCache(DiscordApiImpl.java:679) ~[javacord-3.0.3.jar!/:na]
>         at org.javacord.core.util.handler.channel.ChannelDeleteHandler.handle(ChannelDeleteHandler.java:45) ~[javacord-3.0.3.jar!/:na]
>         at org.javacord.core.util.gateway.PacketHandler.lambda$handlePacket$0(PacketHandler.java:52) ~[javacord-3.0.3.jar!/:na]
>         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
>         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
>         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
>         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
>         at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
```
I guess not the same cause, but these issues started today... I'm Bad_Mate on Discord btw.

**Comment by coaxial1** [comment]
And another one
```
 Couldn't handle packet of type GUILD_CREATE. Please contact the developer! (packet: {"voice_states":[],"verifi
cation_level":0,"unavailable":false,"system_channel_id":"507105352991375370","splash":null,"roles":[{"position":20,"permissions":37035016,"name":"Rythm Musik Bots","mentionable":false,"managed":false,"id":"51127
0871835475979","hoist":false,"color":10070709},{"position":39,"permissions":37035008,"name":"⚡80+⚡","mentionable":false,"managed":false,"id":"509824385067253781","hoist":true,"color":11429888},{"position":24,"pe
rmissions":104143872,"name":"Join+","mentionable":false,"managed":false,"id":"512731786799874079","hoist":false,"color":0},{"position":0,"permissions":37035008,"name":"@everyone","mentionable":false,"managed":fa
lse,"id":"502144461564936192","hoist":false,"color":0},{"position":47,"permissions":805694679,"name":"UnbelievaBoat","mentionable":false,"managed":true,"id":"502146933414952961","hoist":false,"color":5007478},{"
position":42,"permissions":402128082,"name":"💎Supporter\n💎","mentionable":false,"managed":false,"id":"510200312724848642","hoist":true,"color":255},{"position":25,"permissions":262216,"name":"BoobBot","mention
le":false,"managed":true,"id":"511990766365835284","hoist":false,"color":0},{"position":15,"permissions":37035072,"name":"new role","mentionable":false,"managed":false,"id":"519970405557993513","hoist":false,"co
lor":0},{"position":45,"permissions":2146958591,"name":"👑OWNER👑","mentionable":false,"managed":false,"id":"507296454453493771","hoist":true,"color":9109504},{"position":5,"permissions":262216,"name":"Applicati
 Bot","mentionable":false,"managed":true,"id":"530866635234607106","hoist":false,"color":0},{"position":30,"permissions":37215232,"name":"DJ","mentiona ........
```

**Comment by Vampire** [comment]
The last two are new and are actually not present in the official Javacord release.
Those are caused by faulty implementation in #436 which you use.
You should post those exception at the PR and delete them here.

**Comment by coaxial1** [comment]
I'm seeing this now really often in my logs, sadly.

**Comment by Bastian** [comment]
Closing this in favor of #450 which covers this issue.
