### ISSUE TITLE
AssertionError on MESSAGE_REACTION_ADD

### ISSUE THREAD

**Issue by coaxial1** [Javacord/Javacord#439]
````
2019-02-23 22:32:05.636  WARN 21301 --- [dlers Processor] o.j.core.util.gateway.PacketHandler      : Couldn't handle packet of type MESSAGE_REACTION_ADD. Please contact the developer! (packet: {"user_id":"464748
338294816770","message_id":"547024765911826440","emoji":{"name":"Atlantis","id":"485070864849698827","animated":false},"channel_id":"510091032961220619","guild_id":"411246417714216960"})

java.lang.AssertionError: null
        at java.base/java.util.Optional.orElseThrow(Optional.java:408) ~[na:na]
        at org.javacord.core.util.handler.message.reaction.MessageReactionAddHandler.lambda$handle$1(MessageReactionAddHandler.java:37) ~[javacord-3.0.3.jar!/:na]
        at java.base/java.util.Optional.ifPresent(Optional.java:183) ~[na:na]
        at org.javacord.core.util.handler.message.reaction.MessageReactionAddHandler.handle(MessageReactionAddHandler.java:35) ~[javacord-3.0.3.jar!/:na]
        at org.javacord.core.util.gateway.PacketHandler.lambda$handlePacket$0(PacketHandler.java:52) ~[javacord-3.0.3.jar!/:na]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]`
```

**Comment by burdoto** [comment]
This might be related to #440

**Comment by Bastian** [comment]
Closing this in favor of #450 which covers this issue.
