### ISSUE TITLE
Owner not cached

### ISSUE THREAD

**Issue by coaxial1** [Javacord/Javacord#440]
```
java.lang.IllegalStateException: Owner of server Server (id: 546064141807386635, name: RU Ranked Scrims) is not cached!
        at org.javacord.core.entity.server.ServerImpl.lambda$getOwner$10(ServerImpl.java:851) ~[javacord-3.0.3.jar!/:na]
        at java.base/java.util.Optional.orElseThrow(Optional.java:408) ~[na:na]
        at org.javacord.core.entity.server.ServerImpl.getOwner(ServerImpl.java:851) ~[javacord-3.0.3.jar!/:na]
        at xyz.yunite.core.plugins.reg.SupportServerRolePlugin.lambda$new$0(SupportServerRolePlugin.java:51) ~[classes!/:0.0.1-SNAPSHOT]
        at java.base/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90) ~[na:na]
        at java.base/java.util.HashMap$KeySpliterator.tryAdvance(HashMap.java:1624) ~[na:na]
        at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[na:na]
        at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) ~[na:na]
        at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
        at java.base/java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:528) ~[na:na]
        at xyz.yunite.core.plugins.reg.SupportServerRolePlugin.lambda$new$3(SupportServerRolePlugin.java:49) ~[classes!/:0.0.1-SNAPSHOT]
       [...]
```
Saw this one time in the logs, thrown on Server#getOwner

**Comment by Bastian** [comment]
Closing this in favor of #450 which covers this issue.
