### ISSUE TITLE
User with presences not cached

### ISSUE THREAD

**Issue by coaxial1** [Javacord/Javacord#442]
```
java.lang.AssertionError: null
        at java.base/java.util.Optional.orElseThrow(Optional.java:408) ~[na:na]
        at org.javacord.core.entity.server.ServerImpl.<init>(ServerImpl.java:322) ~[javacord-3.0.3.jar!/:na]
        at org.javacord.core.util.handler.guild.GuildCreateHandler.handle(GuildCreateHandler.java:34) ~[javacord-3.0.3.jar!/:na]
        at org.javacord.core.util.gateway.PacketHandler.lambda$handlePacket$0(PacketHandler.java:52) ~[javacord-3.0.3.jar!/:na]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at org.javacord.core.util.gateway.PacketHandler.lambda$handlePacket$0(PacketHandler.java:52) ~[javacord-3.0.3.jar!/:na]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
```

This exception is accompanied by a very long log message, probably a guild create event or something. It is too long to fit in my terminal cache, but ends with 

```
132","deny":0,"allow":1024},{"type":"role","id":"546214999928864768","deny":0,"allow":1024}],"parent_id":"546049828443127859","name":"rules-customs","last_message_id":"547878095785426945","id":"54683287576536681
4"},{"user_limit":0,"type":4,"position":10,"permission_overwrites":[{"type":"role","id":"285894122349527040","deny":1051648,"allow":0}],"name":"Disabled","id":"543092410448609322","bitrate":64000},{"type":0,"top
ic":null,"rate_limit_per_user":0,"position":47,"permission_overwrites":[{"type":"role","id":"285894122349527040","deny":1024,"allow":0},{"type":"role","id":"486652518420709387","deny":2048,"allow":0},{"type":"ro
le","id":"460941408379994132","deny":0,"allow":1024}],"parent_id":"438444537640386560","name":"gaius","last_message_id":"550097271623254016","id":"522593135860252701"},{"user_limit":0,"type":4,"position":4,"perm
ission_overwrites":[{"type":"role","id":"285894122349527040","deny":2048,"allow":1024},{"type":"role","id":"548622141604757515","deny":0,"allow":1024},{"type":"role","id":"548621920862601236","deny":0,"allow":10
alow":0},{"type":"role","id":"462930038178709516","deny":0,"allow":1024},{"type":"role","id":"460941408379994132","deny":0,"allow":1024}],"parent_id":"467333477608718339","name":"pro-lounge","last_pin_timestamp"
:"2018-07-13T14:19:34.248000+00:00","last_message_id":"467334276850122752","id":"467012209008967711"},{"type":0,"topic":null,"rate_limit_per_user":0,"position":17,"permission_overwrites":[{"type":"role","id":"28
5894122349527040","deny":1049600,"allow":0},{"type":"role","id":"285896214983999488","deny":0,"allow":1049600},{"type":"role","id":"461668490538123274","deny":0,"allow":1024},{"type":"role","id":"486652518420709
387","deny":2112,"allow":0},{"type":"role","id":"481555505261707281","deny":0,"allow":132096},{"type":"role","id":"460941408379994132","deny":0,"allow":1024}],"parent_id":"438444321340129310","name":"staff-chat-
eu","last_message_id":"549267926126034984","id":"481555286734143498"},{"type":0,"topic":"","rate_limit_per_user":30,"position":28,"permission_overwrites":[{"type":"role","id":"285894122349527040","deny":2048,"al
low":1024},{"type":"role","id":"285896214983999488","deny":0,"allow":1024},{"type":"role","id":"473608656479322112","deny":2097152,"allow":1024},{"type":"role","id":"473499480214339585","deny":0,"allow":16788800
},{"type":"role","id":"462929325902266378","deny":0,"allow":1024},{"type":"role","id":"486652518420709387","deny":2112,"allow":0},{"type":"role","id":"460941408379994132","deny":0,"allow":1024},{"type":"role","i
d":"481555740478144522","deny":0,"allow":9216},{"type":"role","id":"531633633899839488","deny":0,"allow":268696592}],"parent_id":"477571724452560907","nsfw":false,"name":"na-match-info","last_pin_timestamp":"201
9-02-16T22:16:07.928000+00:00","last_message_id":"550099260264284161","id":"500046559002624010"},{"type":0,"topic":"","rate_limit_per_user":0,"position":19,"permission_overwrites":[{"type":"role","id":"285894122
349527040","deny":1049600,"allow":0},{"type":"role","id":"285896214983999488","deny":0,"allow":0},{"type":"role","id":"495932349515694080","deny":0,"allow":1024},{"type":"role","id":"461668490538123274","deny":0
,"allow":1024},{"type":"role","id":"486652518420709387","deny":2112,"allow":0},{"type":"role","id":"495967637893939210","deny":0,"allow":1024},{"type":"role","id":"460941408379994132","deny":0,"allow":1024},{"ty
pe":"role","id":"486249084995239946","deny":0,"allow":1024},{"type":"role","id":"497955164553216030","deny":0,"allow":1024}],"parent_id":"438444321340129310","name":"staff-former-inactive","last_message_id":"537
854713253855232","id":"497683145630416896"},{"user_limit":0,"type":4,"position":3,"permission_overwrites":[{"type":"role","id":"285894122349527040","deny":1049600,"allow":0},{"type":"role","id":"4866525184207093
_imit_per_user":120,"position":49,"permission_overwrites":[{"type":"role","id":"285894122349527040","deny":1051648,"allow":0}],"parent_id":"543092410448609322","name":"submit-cake","last_pin_timestamp":"2019-01-
30T22:04:06.101000+00:00","last_message_id":"545642156040388620","id":"540290066816434176"}],"application_id":null,"afk_timeout":900,"afk_channel_id":null})
```

This happens now at least one time on every startup.

**Comment by burdoto** [comment]
This is related to #439 and #440; which might be related to #261.

**Comment by Bastian** [comment]
@burdoto No, these issues are not related, even though they look very similar.
This is a Discord bug:
![presence-user-not-in-members](https://user-images.githubusercontent.com/5033001/54230647-2509d600-4507-11e9-8faf-3db03f0f7c6c.png)

While not being the same issue, it's still very similar to https://github.com/discordapp/discord-api-docs/issues/855
