### ISSUE TITLE
java.lang.IllegalStateException when connecting

### ISSUE THREAD

**Issue by SuperMarcomen** [Javacord/Javacord#449]
I have the same issue with the code that is on the readme.
https://github.com/Javacord/Javacord/issues/42

**Comment by Vampire** [comment]
If you have the same issue, don't use Javacord v2.
If you are using Javacord v3, you are not having the same issue, as it is a nearly complete rewrite.
In the latter case, please provide proper information like version, stacktrace, error message and so on.

**Comment by SuperMarcomen** [comment]
I'm using the version 3.0.3

`2019-03-10 18:58:21.638+0100 INFO org.javacord.core.util.logging.ExceptionLoggerDelegateImpl No Log4j2 compatible logger was found. Using default Javacord implementation!
2019-03-10 18:58:23.157+0100 INFO org.javacord.core.util.gateway.DiscordWebSocketAdapter Websocket closed with reason 'Authentication failed.' and code AUTHENTICATION_FAILED (4004) by server! {shard=0} 
Exception in thread "main" java.util.concurrent.CompletionException: java.lang.IllegalStateException: Websocket closed before READY packet was received!
	at java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:375)
	at java.util.concurrent.CompletableFuture.join(CompletableFuture.java:1934)
	at net.etheria.tickets.bots.discord.DiscordBot.main(DiscordBot.java:14)
Caused by: java.lang.IllegalStateException: Websocket closed before READY packet was received!
	at org.javacord.core.DiscordApiImpl.lambda$new$3(DiscordApiImpl.java:458)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
	at org.javacord.core.util.gateway.DiscordWebSocketAdapter.onDisconnected(DiscordWebSocketAdapter.java:464)
	at com.neovisionaries.ws.client.ListenerManager.callOnDisconnected(ListenerManager.java:223)
	at com.neovisionaries.ws.client.WebSocket.finish(WebSocket.java:3713)
	at com.neovisionaries.ws.client.WebSocket.onThreadsFinished(WebSocket.java:3683)
	at com.neovisionaries.ws.client.WebSocket.onWritingThreadFinished(WebSocket.java:3672)
	at com.neovisionaries.ws.client.WritingThread.notifyFinished(WritingThread.java:539)
	at com.neovisionaries.ws.client.WritingThread.runMain(WritingThread.java:78)
	at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)`

**Comment by Vampire** [comment]
Ok, so which part of `'Authentication failed.'` is unclear? ;-)
Your token is wrong.

**Comment by SuperMarcomen** [comment]
Thak you, I was actually using the "Client secret" instead of the token, This is my first time with a Discord bot. I'm sorry.
