### ISSUE TITLE
EventDispatcherBase stuck

### ISSUE THREAD

**Issue by Bastian** [Javacord/Javacord#458]
The event dispatcher gets stuck and causes the bot to no longer call any listeners (tested with a `MessageCreateListener`). This needs some more investigation.

Here#s a thread dump of the bot:
```
2019-03-24 12:39:21
Full thread dump Java HotSpot(TM) 64-Bit Server VM (9.0.1+11 mixed mode):

"Javacord - Central ExecutorService - 8" #39 prio=5 os_prio=0 tid=0x0000011480309800 nid=0x748 waiting on condition [0x000000064cefe000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@9.0.1/Native Method)
	- parking to wait for  <0x000000040020e210> (a java.util.concurrent.SynchronousQueue$TransferStack)
	at java.util.concurrent.locks.LockSupport.parkNanos(java.base@9.0.1/LockSupport.java:234)
	at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(java.base@9.0.1/SynchronousQueue.java:462)
	at java.util.concurrent.SynchronousQueue$TransferStack.transfer(java.base@9.0.1/SynchronousQueue.java:361)
	at java.util.concurrent.SynchronousQueue.poll(java.base@9.0.1/SynchronousQueue.java:937)
	at java.util.concurrent.ThreadPoolExecutor.getTask(java.base@9.0.1/ThreadPoolExecutor.java:1091)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@9.0.1/ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@9.0.1/ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(java.base@9.0.1/Thread.java:844)

"Javacord - Central ExecutorService - 7" #38 prio=5 os_prio=0 tid=0x000001148030a800 nid=0x1110 in Object.wait() [0x000000064cbfe000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(java.base@9.0.1/Native Method)
	- waiting on <no object reference available>
	at org.javacord.core.util.event.EventDispatcherBase.lambda$checkRunningListenersAndStartIfPossible$18(EventDispatcherBase.java:257)
	- waiting to re-lock in wait() <0x00000004f3fb0e48> (a java.lang.Object)
	at org.javacord.core.util.event.EventDispatcherBase$$Lambda$366/833144006.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(java.base@9.0.1/Executors.java:514)
	at java.util.concurrent.FutureTask.run(java.base@9.0.1/FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@9.0.1/ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@9.0.1/ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(java.base@9.0.1/Thread.java:844)

"Javacord - Central ExecutorService - 6" #37 prio=5 os_prio=0 tid=0x0000011480307800 nid=0x24f4 in Object.wait() [0x000000064a1fe000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(java.base@9.0.1/Native Method)
	- waiting on <0x00000004fff046d0> (a java.lang.Object)
	at org.javacord.core.util.event.EventDispatcherBase.lambda$checkRunningListenersAndStartIfPossible$18(EventDispatcherBase.java:257)
	- waiting to re-lock in wait() <0x00000004fff046d0> (a java.lang.Object)
	at org.javacord.core.util.event.EventDispatcherBase$$Lambda$366/833144006.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(java.base@9.0.1/Executors.java:514)
	at java.util.concurrent.FutureTask.run(java.base@9.0.1/FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@9.0.1/ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@9.0.1/ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(java.base@9.0.1/Thread.java:844)

"Javacord - Central ExecutorService - 5" #36 prio=5 os_prio=0 tid=0x000001148030c000 nid=0x3088 in Object.wait() [0x000000064caff000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(java.base@9.0.1/Native Method)
	- waiting on <0x0000000502b00870> (a java.lang.Object)
	at org.javacord.core.util.event.EventDispatcherBase.lambda$checkRunningListenersAndStartIfPossible$18(EventDispatcherBase.java:257)
	- waiting to re-lock in wait() <0x0000000502b00870> (a java.lang.Object)
	at org.javacord.core.util.event.EventDispatcherBase$$Lambda$366/833144006.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(java.base@9.0.1/Executors.java:514)
	at java.util.concurrent.FutureTask.run(java.base@9.0.1/FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@9.0.1/ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@9.0.1/ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(java.base@9.0.1/Thread.java:844)

"Javacord - Central ExecutorService - 4" #35 prio=5 os_prio=0 tid=0x0000011480308000 nid=0xec8 in Object.wait() [0x000000064a3fe000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(java.base@9.0.1/Native Method)
	- waiting on <0x00000004a2e00218> (a java.lang.Object)
	at org.javacord.core.util.event.EventDispatcherBase.lambda$checkRunningListenersAndStartIfPossible$18(EventDispatcherBase.java:257)
	- waiting to re-lock in wait() <0x00000004a2e00218> (a java.lang.Object)
	at org.javacord.core.util.event.EventDispatcherBase$$Lambda$366/833144006.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(java.base@9.0.1/Executors.java:514)
	at java.util.concurrent.FutureTask.run(java.base@9.0.1/FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@9.0.1/ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@9.0.1/ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(java.base@9.0.1/Thread.java:844)

"Javacord - Central ExecutorService - 3" #34 prio=5 os_prio=0 tid=0x0000011480309000 nid=0x908 in Object.wait() [0x000000064a2ff000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(java.base@9.0.1/Native Method)
	- waiting on <0x00000004a2e00228> (a java.lang.Object)
	at org.javacord.core.util.event.EventDispatcherBase.lambda$checkRunningListenersAndStartIfPossible$18(EventDispatcherBase.java:257)
	- waiting to re-lock in wait() <0x00000004a2e00228> (a java.lang.Object)
	at org.javacord.core.util.event.EventDispatcherBase$$Lambda$366/833144006.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(java.base@9.0.1/Executors.java:514)
	at java.util.concurrent.FutureTask.run(java.base@9.0.1/FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@9.0.1/ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@9.0.1/ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(java.base@9.0.1/Thread.java:844)

"DestroyJavaVM" #33 prio=5 os_prio=0 tid=0x0000011480304800 nid=0xd50 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Javacord - Event Dispatch Queues Manager" #30 prio=5 os_prio=0 tid=0x000001148030b000 nid=0xfdc waiting on condition [0x000000064d6ff000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@9.0.1/Native Method)
	- parking to wait for  <0x0000000410b7ec20> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(java.base@9.0.1/LockSupport.java:234)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(java.base@9.0.1/AbstractQueuedSynchronizer.java:2104)
	at java.util.concurrent.LinkedBlockingQueue.poll(java.base@9.0.1/LinkedBlockingQueue.java:460)
	at java.util.concurrent.ThreadPoolExecutor.getTask(java.base@9.0.1/ThreadPoolExecutor.java:1091)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@9.0.1/ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@9.0.1/ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(java.base@9.0.1/Thread.java:844)

"Javacord - Handlers Processor" #29 prio=5 os_prio=0 tid=0x0000011480305000 nid=0x534 waiting on condition [0x000000064d5ff000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@9.0.1/Native Method)
	- parking to wait for  <0x000000040312cdf8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(java.base@9.0.1/LockSupport.java:234)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(java.base@9.0.1/AbstractQueuedSynchronizer.java:2104)
	at java.util.concurrent.LinkedBlockingQueue.poll(java.base@9.0.1/LinkedBlockingQueue.java:460)
	at java.util.concurrent.ThreadPoolExecutor.getTask(java.base@9.0.1/ThreadPoolExecutor.java:1091)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@9.0.1/ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@9.0.1/ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(java.base@9.0.1/Thread.java:844)

"Javacord - Request Server Members Queue Consumer" #27 daemon prio=5 os_prio=0 tid=0x000001148034c800 nid=0xf70 waiting on condition [0x000000064d3fe000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@9.0.1/Native Method)
	- parking to wait for  <0x0000000402da8ab0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(java.base@9.0.1/LockSupport.java:234)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(java.base@9.0.1/AbstractQueuedSynchronizer.java:2104)
	at java.util.concurrent.LinkedBlockingQueue.poll(java.base@9.0.1/LinkedBlockingQueue.java:460)
	at org.javacord.core.util.gateway.DiscordWebSocketAdapter.lambda$new$4(DiscordWebSocketAdapter.java:203)
	at org.javacord.core.util.gateway.DiscordWebSocketAdapter$$Lambda$154/200092454.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(java.base@9.0.1/Executors.java:514)
	at java.util.concurrent.FutureTask.run(java.base@9.0.1/FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@9.0.1/ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@9.0.1/ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(java.base@9.0.1/Thread.java:844)

"ReadingThread" #25 prio=5 os_prio=0 tid=0x000001148034f800 nid=0x35f8 runnable [0x000000064d1ff000]
   java.lang.Thread.State: RUNNABLE
	at java.net.SocketInputStream.socketRead0(java.base@9.0.1/Native Method)
	at java.net.SocketInputStream.socketRead(java.base@9.0.1/SocketInputStream.java:116)
	at java.net.SocketInputStream.read(java.base@9.0.1/SocketInputStream.java:171)
	at java.net.SocketInputStream.read(java.base@9.0.1/SocketInputStream.java:141)
	at sun.security.ssl.SSLSocketInputRecord.read(java.base@9.0.1/SSLSocketInputRecord.java:425)
	at sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(java.base@9.0.1/SSLSocketInputRecord.java:65)
	at sun.security.ssl.SSLSocketImpl.bytesInCompletePacket(java.base@9.0.1/SSLSocketImpl.java:918)
	- locked <0x0000000410b929f8> (a java.lang.Object)
	at sun.security.ssl.AppInputStream.read(java.base@9.0.1/AppInputStream.java:144)
	- locked <0x0000000410b94ac8> (a sun.security.ssl.AppInputStream)
	at java.io.BufferedInputStream.fill(java.base@9.0.1/BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(java.base@9.0.1/BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(java.base@9.0.1/BufferedInputStream.java:345)
	- locked <0x0000000410b94ae8> (a java.io.BufferedInputStream)
	at java.io.FilterInputStream.read(java.base@9.0.1/FilterInputStream.java:133)
	at com.neovisionaries.ws.client.WebSocketInputStream.readBytes(WebSocketInputStream.java:165)
	at com.neovisionaries.ws.client.WebSocketInputStream.readFrame(WebSocketInputStream.java:46)
	at com.neovisionaries.ws.client.ReadingThread.readFrame(ReadingThread.java:338)
	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:99)
	at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
	at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)

"OkHttp ConnectionPool" #21 daemon prio=5 os_prio=0 tid=0x0000011480ac8800 nid=0xcdc in Object.wait() [0x000000064cdfe000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(java.base@9.0.1/Native Method)
	- waiting on <0x0000000410bb98f8> (a okhttp3.ConnectionPool)
	at java.lang.Object.wait(java.base@9.0.1/Object.java:474)
	at okhttp3.ConnectionPool$1.run(ConnectionPool.java:67)
	- waiting to re-lock in wait() <0x0000000410bb98f8> (a okhttp3.ConnectionPool)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@9.0.1/ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@9.0.1/ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(java.base@9.0.1/Thread.java:844)

"OkHttp discordapp.com" #20 prio=5 os_prio=0 tid=0x0000011480ac7800 nid=0x3720 runnable [0x000000064ccfe000]
   java.lang.Thread.State: RUNNABLE
	at java.net.SocketInputStream.socketRead0(java.base@9.0.1/Native Method)
	at java.net.SocketInputStream.socketRead(java.base@9.0.1/SocketInputStream.java:116)
	at java.net.SocketInputStream.read(java.base@9.0.1/SocketInputStream.java:171)
	at java.net.SocketInputStream.read(java.base@9.0.1/SocketInputStream.java:141)
	at sun.security.ssl.SSLSocketInputRecord.read(java.base@9.0.1/SSLSocketInputRecord.java:425)
	at sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(java.base@9.0.1/SSLSocketInputRecord.java:65)
	at sun.security.ssl.SSLSocketImpl.bytesInCompletePacket(java.base@9.0.1/SSLSocketImpl.java:918)
	- locked <0x0000000410ba73e8> (a java.lang.Object)
	at sun.security.ssl.AppInputStream.read(java.base@9.0.1/AppInputStream.java:144)
	- locked <0x0000000410ba7540> (a sun.security.ssl.AppInputStream)
	at okio.Okio$2.read(Okio.java:139)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
	at okio.RealBufferedSource.request(RealBufferedSource.java:67)
	at okio.RealBufferedSource.require(RealBufferedSource.java:60)
	at okhttp3.internal.http2.Http2Reader.nextFrame(Http2Reader.java:95)
	at okhttp3.internal.http2.Http2Connection$ReaderRunnable.execute(Http2Connection.java:566)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.lang.Thread.run(java.base@9.0.1/Thread.java:844)

"Javacord - Connection Delay Semaphores Starvation Protector" #18 daemon prio=5 os_prio=0 tid=0x0000011480409800 nid=0xda8 waiting on condition [0x000000064c9ff000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@9.0.1/Native Method)
	- parking to wait for  <0x0000000410bb9d60> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(java.base@9.0.1/LockSupport.java:234)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(java.base@9.0.1/AbstractQueuedSynchronizer.java:2104)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(java.base@9.0.1/ScheduledThreadPoolExecutor.java:1131)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(java.base@9.0.1/ScheduledThreadPoolExecutor.java:848)
	at java.util.concurrent.ThreadPoolExecutor.getTask(java.base@9.0.1/ThreadPoolExecutor.java:1092)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@9.0.1/ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@9.0.1/ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(java.base@9.0.1/Thread.java:844)

"Javacord - Central ExecutorService - 1" #17 prio=5 os_prio=0 tid=0x000001148082f000 nid=0x1680 in Object.wait() [0x000000064c8ff000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(java.base@9.0.1/Native Method)
	- waiting on <0x00000004a2c00018> (a java.lang.Object)
	at org.javacord.core.util.event.EventDispatcherBase.lambda$checkRunningListenersAndStartIfPossible$18(EventDispatcherBase.java:257)
	- waiting to re-lock in wait() <0x00000004a2c00018> (a java.lang.Object)
	at org.javacord.core.util.event.EventDispatcherBase$$Lambda$366/833144006.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(java.base@9.0.1/Executors.java:514)
	at java.util.concurrent.FutureTask.run(java.base@9.0.1/FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@9.0.1/ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@9.0.1/ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(java.base@9.0.1/Thread.java:844)

"Javacord - Central Scheduler - 1" #16 prio=5 os_prio=0 tid=0x0000011480c40000 nid=0x1670 waiting on condition [0x000000064c7ff000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@9.0.1/Native Method)
	- parking to wait for  <0x0000000400209760> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(java.base@9.0.1/LockSupport.java:234)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(java.base@9.0.1/AbstractQueuedSynchronizer.java:2104)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(java.base@9.0.1/ScheduledThreadPoolExecutor.java:1131)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(java.base@9.0.1/ScheduledThreadPoolExecutor.java:848)
	at java.util.concurrent.ThreadPoolExecutor.getTask(java.base@9.0.1/ThreadPoolExecutor.java:1092)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@9.0.1/ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@9.0.1/ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(java.base@9.0.1/Thread.java:844)

"Service Thread" #13 daemon prio=9 os_prio=0 tid=0x00000114fe6c9000 nid=0x34bc runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Monitor Ctrl-Break" #12 daemon prio=5 os_prio=0 tid=0x00000114fea78800 nid=0x3674 runnable [0x000000064c4fe000]
   java.lang.Thread.State: RUNNABLE
	at java.net.SocketInputStream.socketRead0(java.base@9.0.1/Native Method)
	at java.net.SocketInputStream.socketRead(java.base@9.0.1/SocketInputStream.java:116)
	at java.net.SocketInputStream.read(java.base@9.0.1/SocketInputStream.java:171)
	at java.net.SocketInputStream.read(java.base@9.0.1/SocketInputStream.java:141)
	at sun.nio.cs.StreamDecoder.readBytes(java.base@9.0.1/StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(java.base@9.0.1/StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(java.base@9.0.1/StreamDecoder.java:178)
	- locked <0x0000000400209c40> (a java.io.InputStreamReader)
	at java.io.InputStreamReader.read(java.base@9.0.1/InputStreamReader.java:185)
	at java.io.BufferedReader.fill(java.base@9.0.1/BufferedReader.java:161)
	at java.io.BufferedReader.readLine(java.base@9.0.1/BufferedReader.java:326)
	- locked <0x0000000400209c40> (a java.io.InputStreamReader)
	at java.io.BufferedReader.readLine(java.base@9.0.1/BufferedReader.java:392)
	at com.intellij.rt.execution.application.AppMainV2$1.run(AppMainV2.java:64)

"Common-Cleaner" #11 daemon prio=8 os_prio=1 tid=0x00000114fe425000 nid=0x3704 in Object.wait() [0x000000064c3ff000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(java.base@9.0.1/Native Method)
	- waiting on <0x000000040020a9e8> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(java.base@9.0.1/ReferenceQueue.java:151)
	- waiting to re-lock in wait() <0x000000040020a9e8> (a java.lang.ref.ReferenceQueue$Lock)
	at jdk.internal.ref.CleanerImpl.run(java.base@9.0.1/CleanerImpl.java:148)
	at java.lang.Thread.run(java.base@9.0.1/Thread.java:844)
	at jdk.internal.misc.InnocuousThread.run(java.base@9.0.1/InnocuousThread.java:122)

"Sweeper thread" #10 daemon prio=9 os_prio=2 tid=0x00000114fe351800 nid=0x530 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C1 CompilerThread3" #9 daemon prio=9 os_prio=2 tid=0x00000114fe348800 nid=0x36d0 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   No compile task

"C2 CompilerThread2" #8 daemon prio=9 os_prio=2 tid=0x00000114fe33c800 nid=0x15ec waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   No compile task

"C2 CompilerThread1" #7 daemon prio=9 os_prio=2 tid=0x00000114fe33b800 nid=0x2f4 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   No compile task

"C2 CompilerThread0" #6 daemon prio=9 os_prio=2 tid=0x00000114fe33b000 nid=0x36d8 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   No compile task

"Attach Listener" #5 daemon prio=5 os_prio=2 tid=0x00000114fe338000 nid=0x34d0 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Signal Dispatcher" #4 daemon prio=9 os_prio=2 tid=0x00000114fe337800 nid=0x3348 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Finalizer" #3 daemon prio=8 os_prio=1 tid=0x00000114fe2df000 nid=0x2314 in Object.wait() [0x000000064bbff000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(java.base@9.0.1/Native Method)
	- waiting on <0x000000040020e980> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(java.base@9.0.1/ReferenceQueue.java:151)
	- waiting to re-lock in wait() <0x000000040020e980> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(java.base@9.0.1/ReferenceQueue.java:172)
	at java.lang.ref.Finalizer$FinalizerThread.run(java.base@9.0.1/Finalizer.java:216)

"Reference Handler" #2 daemon prio=10 os_prio=2 tid=0x00000114fe2d9800 nid=0xae4 waiting on condition [0x000000064baff000]
   java.lang.Thread.State: RUNNABLE
	at java.lang.ref.Reference.waitForReferencePendingList(java.base@9.0.1/Native Method)
	at java.lang.ref.Reference.processPendingReferences(java.base@9.0.1/Reference.java:174)
	at java.lang.ref.Reference.access$000(java.base@9.0.1/Reference.java:44)
	at java.lang.ref.Reference$ReferenceHandler.run(java.base@9.0.1/Reference.java:138)

"VM Thread" os_prio=2 tid=0x00000114fdace000 nid=0xae8 runnable 

"GC Thread#0" os_prio=2 tid=0x00000114cb2a1000 nid=0xdc4 runnable 

"GC Thread#1" os_prio=2 tid=0x00000114cb2a2800 nid=0xa8c runnable 

"GC Thread#2" os_prio=2 tid=0x00000114cb2a5000 nid=0xc74 runnable 

"GC Thread#3" os_prio=2 tid=0x00000114cb2a6000 nid=0xb80 runnable 

"GC Thread#4" os_prio=2 tid=0x00000114cb2a8800 nid=0xbb8 runnable 

"GC Thread#5" os_prio=2 tid=0x00000114cb2b2000 nid=0xbb4 runnable 

"GC Thread#6" os_prio=2 tid=0x00000114cb2b2800 nid=0x1954 runnable 

"GC Thread#7" os_prio=2 tid=0x00000114cb2b0000 nid=0x12b0 runnable 

"G1 Main Marker" os_prio=2 tid=0x00000114fadf5000 nid=0x1ec8 runnable 

"G1 Marker#0" os_prio=2 tid=0x00000114cb2b3800 nid=0xc14 runnable 

"G1 Marker#1" os_prio=2 tid=0x00000114cb2b1000 nid=0x3694 runnable 

"G1 Refine#0" os_prio=2 tid=0x00000114cb2d9800 nid=0xab4 runnable 

"G1 Refine#1" os_prio=2 tid=0x00000114cb2d8800 nid=0x36a8 runnable 

"G1 Refine#2" os_prio=2 tid=0x00000114cb2d8000 nid=0x1234 runnable 

"G1 Refine#3" os_prio=2 tid=0x00000114cb2d7000 nid=0xbc8 runnable 

"G1 Refine#4" os_prio=2 tid=0x00000114cb2d6800 nid=0x3340 runnable 

"G1 Refine#5" os_prio=2 tid=0x00000114cb2d4000 nid=0x3a58 runnable 

"G1 Refine#6" os_prio=2 tid=0x00000114cb2d1800 nid=0x14b8 runnable 

"G1 Refine#7" os_prio=2 tid=0x00000114cb2c3800 nid=0x1948 runnable 

"G1 Young RemSet Sampling" os_prio=2 tid=0x00000114cb2dc000 nid=0x34e0 runnable 

"VM Periodic Task Thread" os_prio=2 tid=0x00000114fe6cd800 nid=0x39e4 waiting on condition 

JNI global references: 1194

Heap
 garbage-first heap   total 4268032K, used 1683378K [0x0000000400000000, 0x0000000400204120, 0x0000000600000000)
  region size 2048K, 282 young (577536K), 25 survivors (51200K)
 Metaspace       used 30404K, capacity 32136K, committed 32256K, reserved 1077248K
  class space    used 3233K, capacity 3568K, committed 3584K, reserved 1048576K
```

**Comment by Bastian** [comment]
Seems like the websocket can just not keep up with the amount of incoming packets.
