### ISSUE TITLE
Error when running gradle jar.  By java.lang.ClassNotFoundException: de.btobastian.sdcf4j.CommandExecutor

### ISSUE THREAD

**Issue by laskdjlaskdj12** [Javacord/Javacord#466]
After build by jar file and run by java -jar i've got this

```
Exception in thread "main" java.lang.NoClassDefFoundError: de/btobastian/sdcf4j/CommandExecutor
        at com.laskdjlaskdj12.gamster.Application.main(Application.java:7)
Caused by: java.lang.ClassNotFoundException: de.btobastian.sdcf4j.CommandExecutor
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 1 more
```

and also this my gradle file source 

```
plugins {
    id 'java'
}

group 'com.laskdjlaskdj12.gamster'
version '1.0-SNAPSHOT'

sourceCompatibility = 1.8

repositories {
    jcenter()
    mavenCentral()
    maven { url 'https://jitpack.io'}
}
jar{
    manifest {
        attributes  'Title': 'gamster4j', 'Version': version, 'Main-Class': 'com.laskdjlaskdj12.gamster.Application'
    }
    from { configurations.compile.collect { it.isDirectory() ? it : zipTree(it) } }
}

dependencies {
    compileOnly 'org.projectlombok:lombok:1.18.6'
    annotationProcessor 'org.projectlombok:lombok:1.18.6'
    implementation group: 'de.btobastian.sdcf4j', name: 'sdcf4j-core', version: '1.0.10'
    implementation group: 'de.btobastian.sdcf4j', name: 'sdcf4j-jda3', version: '1.0.10'
    implementation('net.dv8tion:JDA:3.7.1_385') {
        exclude module: 'opus-java'
    }
    testCompile group: 'junit', name: 'junit', version: '4.12'
    compile group: 'com.google.code.gson', name: 'gson', version: '2.8.5'
    compile group: 'org.apache.commons', name: 'commons-lang3', version: '3.4'
    compile group: 'commons-io', name: 'commons-io', version: '2.6'
    compile group: 'org.slf4j', name: 'slf4j-simple', version: '1.7.25'
    testCompile group: 'org.mockito', name: 'mockito-all', version: '1.10.19'
}

```

**Comment by burdoto** [comment]
This issue does not belong into the Javacord repository, as you clearly are using JDA and the JDA artifact of SDCF4J. Please use the [proper repository](https://github.com/Bastian/sdcf4j) and reopen the issue there.
