### ISSUE TITLE
Couldn't handle packet of type CHANNEL_CREATE,

### ISSUE THREAD

**Issue by GhostHacks96** [Javacord/Javacord#484]
Hello, ive looked at the issues that where closed but they offered no help, so i hope this can provide more help to anyone having the same issue as me.

Ive created a bot to create and delete text and voice channels to sync with a game server teams, however I'm getting packet handling  errors here is the stack trace i get when the bot auto creates the channels.

`[00:26:28] [Server thread/ERROR]: §8[§3DiscordSync§8]§r§aCreating Channels
[00:26:28] [Server thread/ERROR]: §8[§3DiscordSync§8]§r§aText Channel Created!
[00:26:28] [Server thread/ERROR]: §8[§3DiscordSync§8]§r§aVoice Channel Created!
[00:26:28] [Javacord - Handlers Processor/WARN]: Couldn't handle packet of type CHANNEL_CREATE. Please contact the developer! (packet: {"type":0,"topic":null,"rate_limit_per_user":0,"position":4,"permission_overwrites":[{"type":"role","id":"358066210992160770","deny":0,"allow":871890257}],"parent_id":"592495655818362886","nsfw":false,"name":"testt","last_message_id":null,"id":"592948707930931200","guild_id":"358065662893096960"})
java.lang.IllegalStateException: zip file closed
	at java.util.zip.ZipFile.ensureOpen(ZipFile.java:686) ~[?:1.8.0_212]
	at java.util.zip.ZipFile.getEntry(ZipFile.java:315) ~[?:1.8.0_212]
	at java.util.jar.JarFile.getEntry(JarFile.java:240) ~[?:1.8.0_212]
	at java.util.jar.JarFile.getJarEntry(JarFile.java:223) ~[?:1.8.0_212]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:97) ~[spigot.jar:git-Spigot-df0eb25-30a6337]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:81) ~[spigot.jar:git-Spigot-df0eb25-30a6337]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_212]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212]
	at org.javacord.core.util.handler.channel.ChannelCreateHandler.handle(ChannelCreateHandler.java:44) ~[?:?]
	at org.javacord.core.util.gateway.PacketHandler.lambda$handlePacket$0(PacketHandler.java:51) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_212]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
`
I've tried to find out what i need to do based on the javadocs and the few examples i could find, however t seems like I'm handling everything correctly. Any help is greatly appreciated!

**Comment by Vampire** [comment]
This has nothing to do with Javacord actually.
It tries to use a class that was not yet loaded. But the plugin class loader of Bukkit has closed the JAR file of your plugin.
I heard this happens when you shutdown and don't wait for the shutdown to finish.
Why it happens for you I don't know without debugging your stuff to see why the plugin JAR was closed.
But there is nothing Javacord could do about it. You need to either complain to Bukkit or debug their class loader to find out why the JAR got closed to see how you maybe can prevent it.

**Comment by GhostHacks96** [comment]
hm, alright I'll look though the class leaders. but it only happens when I add or remove channels so I assumed it was java cord or something I was supposed to register that I hadnt sern. thanks for your help
