### ISSUE TITLE
Exception in thread "main" java.util.concurrent.CompletionException: java.lang.IllegalStateException: Websocket closed before READY packet was received!

### ISSUE THREAD

**Issue by iEvilPanda** [Javacord/Javacord#490]
I know this issue has come up before but I cannot seem to figure out a way to resolve it. I thought I would post my errors and hopefully someone else can help me. I'm stumped.

`Exception in thread "main" java.util.concurrent.CompletionException: java.lang.IllegalStateException: Websocket closed before READY packet was received!
	at java.base/java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:412)
	at java.base/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2044)
	at com.github.iEvilPanda.Main.main(Main.java:11)
Caused by: java.lang.IllegalStateException: Websocket closed before READY packet was received!
	at org.javacord.core.DiscordApiImpl.lambda$new$6(DiscordApiImpl.java:512)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
	at org.javacord.core.util.gateway.DiscordWebSocketAdapter.onDisconnected(DiscordWebSocketAdapter.java:464)
	at com.neovisionaries.ws.client.ListenerManager.callOnDisconnected(ListenerManager.java:223)
	at com.neovisionaries.ws.client.WebSocket.finish(WebSocket.java:3713)
	at com.neovisionaries.ws.client.WebSocket.onThreadsFinished(WebSocket.java:3683)
	at com.neovisionaries.ws.client.WebSocket.onWritingThreadFinished(WebSocket.java:3672)
	at com.neovisionaries.ws.client.WritingThread.notifyFinished(WritingThread.java:539)
	at com.neovisionaries.ws.client.WritingThread.runMain(WritingThread.java:78)
	at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)
`

**Comment by Vampire** [comment]
Usually this means you token is wrong. And this will also be logged one line above that exception.

**Comment by iEvilPanda** [comment]
> 
> 
> Usually this means you token is wrong. And this will also be logged one line above that exception.

I just realized I was using the Client ID not the bot token... Got it working thank you. Can't believe that was my problem.
