### ISSUE TITLE
java.lang.IllegalStateException

### ISSUE THREAD

**Issue by dagobertdu94** [Javacord/Javacord#494]
```
java.lang.ExceptionInInitializerError: null
	at org.javacord.api.DiscordApiBuilder.<init>(DiscordApiBuilder.java:28) ~[?:?]
	at net.dagobertdu94.discord_bot.DiscordBot.<init>(DiscordBot.java:56) ~[?:?]
	at net.dagobertdu94.discord_bot.Main.onEnable(Main.java:45) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.14.4.jar:git-Spigot-065a373-8d4bc54]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [spigot-1.14.4.jar:git-Spigot-065a373-8d4bc54]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417) [spigot-1.14.4.jar:git-Spigot-065a373-8d4bc54]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:461) [spigot-1.14.4.jar:git-Spigot-065a373-8d4bc54]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:375) [spigot-1.14.4.jar:git-Spigot-065a373-8d4bc54]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:449) [spigot-1.14.4.jar:git-Spigot-065a373-8d4bc54]
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:266) [spigot-1.14.4.jar:git-Spigot-065a373-8d4bc54]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:775) [spigot-1.14.4.jar:git-Spigot-065a373-8d4bc54]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.IllegalStateException: No DelegateFactoryDelegate implementation was found!
	at org.javacord.api.util.internal.DelegateFactory.<clinit>(DelegateFactory.java:72) ~[?:?]
	... 12 more
```

I hadn't any problems in the IDE but on my spigot server it doesn't worked. So I can't make a discord bot that will show whether the server is online or not. I am using the 3.0.4 of Javacord.

**Comment by Vampire** [comment]
You broke it by doing the shading wrongly.
Either you didn't shade-in the CORE artifact,
or the service information in META-INF of the CORE artifact.

**Comment by dagobertdu94** [comment]
As the spigot server didn't knew all of the required libraries and classes, I had simply copied all required packages and classes into just one file. After that it has found all classes, but then the factory got a problem. But first I had downloaded Javacord via Gradle.

**Comment by dagobertdu94** [comment]
Now I have copied the complete META-INF Folder, too, but now it can't find the class org.javacord.api.Javacord which I have copied, too.

**Comment by Vampire** [comment]
Basitan wrote a tutorial at https://www.spigotmc.org/threads/create-a-discord-bot-within-a-spigot-plugin.368423/ on how to make a spigot plugin with Javacord shaded in.
He uses Maven in that tutorial, but you can also do it with Gradle (which is always preferable imho).
With Gradle I'd recommend using the https://plugins.gradle.org/plugin/com.github.johnrengelman.shadow plugin to create the JAR with all necessary things shaded in.

**Comment by dagobertdu94** [comment]
Thanks I will take a look at them.

**Comment by dagobertdu94** [comment]
Thanks for the help! Now it works as a spigot plugin on my server.

**Comment by Vampire** [comment]
Then please close the issue :-)
