### ISSUE TITLE
java.lang.VerifyError on trying to connect with a bad token

### ISSUE THREAD

**Issue by burdoto** [Javacord/Javacord#504]
When trying to connect with a bad token [on this project state](https://github.com/comroid-git/Cobalton/tree/08cbea3f416b7204eebd8ab006141631e9518d65), I got a bunch of these as output:
```
2019-11-01 19:56:16.947+0100 WARN org.javacord.core.util.gateway.DiscordWebSocketAdapter An error occurred while connecting to websocket {shard=0} 
 java.util.concurrent.CompletionException: java.lang.VerifyError: Stack map does not match the one at exception handler 77
Exception Details:
  Location:
    com/fasterxml/jackson/databind/deser/std/StdDeserializer._parseDate(Lcom/fasterxml/jackson/core/JsonParser;Lcom/fasterxml/jackson/databind/DeserializationContext;)Ljava/util/Date; @77: astore
  Reason:
    Type 'com/fasterxml/jackson/core/JsonParseException' (current frame, stack[0]) is not assignable to 'com/fasterxml/jackson/core/exc/StreamReadException' (stack map, stack[0])
  Current Frame:
    bci: @69
    flags: { }
    locals: { 'com/fasterxml/jackson/databind/deser/std/StdDeserializer', 'com/fasterxml/jackson/core/JsonParser', 'com/fasterxml/jackson/databind/DeserializationContext' }
    stack: { 'com/fasterxml/jackson/core/JsonParseException' }
  Stackmap Frame:
    bci: @77
    flags: { }
    locals: { 'com/fasterxml/jackson/databind/deser/std/StdDeserializer', 'com/fasterxml/jackson/core/JsonParser', 'com/fasterxml/jackson/databind/DeserializationContext' }
    stack: { 'com/fasterxml/jackson/core/exc/StreamReadException' }
  Bytecode:
    0000000: 2bb6 0035 aa00 0000 0000 0081 0000 0003
    0000010: 0000 000b 0000 007a 0000 0081 0000 0081
    0000020: 0000 0034 0000 0041 0000 0081 0000 0081
    0000030: 0000 0081 0000 0071 2a2b b600 11b6 0012
    0000040: 2cb6 006b b02b b600 4742 a700 223a 052c
    0000050: 2ab4 0002 2bb6 006e 126f 03bd 0004 b600
    0000060: 70c0 002d 3a06 1906 b600 4c42 bb00 7159
    0000070: 21b7 0072 b02a 2cb6 0073 c000 71b0 2a2b
    0000080: 2cb6 0074 b02c 2ab4 0002 2bb6 0025 c000
    0000090: 71b0                                   
  Exception Handler Table:
    bci [69, 74] => handler: 77
    bci [69, 74] => handler: 77
  Stackmap Table:
    same_frame(@56)
    same_frame(@69)
    same_locals_1_stack_item_frame(@77,Object[#359])
    append_frame(@108,Long)
    chop_frame(@117,1)
    same_frame(@126)
    same_frame(@133)

	at java.base/java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:412)
	at java.base/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2044)
	at org.javacord.core.util.gateway.DiscordWebSocketAdapter.getGateway(DiscordWebSocketAdapter.java:260)
	at org.javacord.core.util.gateway.DiscordWebSocketAdapter.connect(DiscordWebSocketAdapter.java:310)
	at org.javacord.core.util.gateway.DiscordWebSocketAdapter.<init>(DiscordWebSocketAdapter.java:195)
	at org.javacord.core.util.gateway.DiscordWebSocketAdapter.<init>(DiscordWebSocketAdapter.java:181)
	at org.javacord.core.DiscordApiImpl.lambda$new$7(DiscordApiImpl.java:481)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.VerifyError: Stack map does not match the one at exception handler 77
Exception Details:
  Location:
    com/fasterxml/jackson/databind/deser/std/StdDeserializer._parseDate(Lcom/fasterxml/jackson/core/JsonParser;Lcom/fasterxml/jackson/databind/DeserializationContext;)Ljava/util/Date; @77: astore
  Reason:
    Type 'com/fasterxml/jackson/core/JsonParseException' (current frame, stack[0]) is not assignable to 'com/fasterxml/jackson/core/exc/StreamReadException' (stack map, stack[0])
  Current Frame:
    bci: @69
    flags: { }
    locals: { 'com/fasterxml/jackson/databind/deser/std/StdDeserializer', 'com/fasterxml/jackson/core/JsonParser', 'com/fasterxml/jackson/databind/DeserializationContext' }
    stack: { 'com/fasterxml/jackson/core/JsonParseException' }
  Stackmap Frame:
    bci: @77
    flags: { }
    locals: { 'com/fasterxml/jackson/databind/deser/std/StdDeserializer', 'com/fasterxml/jackson/core/JsonParser', 'com/fasterxml/jackson/databind/DeserializationContext' }
    stack: { 'com/fasterxml/jackson/core/exc/StreamReadException' }
  Bytecode:
    0000000: 2bb6 0035 aa00 0000 0000 0081 0000 0003
    0000010: 0000 000b 0000 007a 0000 0081 0000 0081
    0000020: 0000 0034 0000 0041 0000 0081 0000 0081
    0000030: 0000 0081 0000 0071 2a2b b600 11b6 0012
    0000040: 2cb6 006b b02b b600 4742 a700 223a 052c
    0000050: 2ab4 0002 2bb6 006e 126f 03bd 0004 b600
    0000060: 70c0 002d 3a06 1906 b600 4c42 bb00 7159
    0000070: 21b7 0072 b02a 2cb6 0073 c000 71b0 2a2b
    0000080: 2cb6 0074 b02c 2ab4 0002 2bb6 0025 c000
    0000090: 71b0                                   
  Exception Handler Table:
    bci [69, 74] => handler: 77
    bci [69, 74] => handler: 77
  Stackmap Table:
    same_frame(@56)
    same_frame(@69)
    same_locals_1_stack_item_frame(@77,Object[#359])
    append_frame(@108,Long)
    chop_frame(@117,1)
    same_frame(@126)
    same_frame(@133)

	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.createTreeDeserializer(BasicDeserializerFactory.java:1448)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:409)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:349)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:264)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
	at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:476)
	at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:4389)
	at com.fasterxml.jackson.databind.ObjectMapper._readTreeAndClose(ObjectMapper.java:4250)
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2711)
	at org.javacord.core.util.rest.RestRequestResult.<init>(RestRequestResult.java:40)
	at org.javacord.core.util.rest.RestRequest.executeBlocking(RestRequest.java:349)
	at org.javacord.core.util.ratelimit.RatelimitManager.lambda$queueRequest$2(RatelimitManager.java:105)
	... 5 more
2019-11-01 19:56:16.953+0100 INFO org.javacord.core.util.gateway.DiscordWebSocketAdapter Trying to reconnect/resume in 1 seconds! {shard=0} 
2019-11-01 19:56:17.996+0100 WARN org.javacord.core.util.gateway.DiscordWebSocketAdapter An error occurred while connecting to websocket {shard=0} 
 java.util.concurrent.CompletionException: java.lang.VerifyError: Stack map does not match the one at exception handler 77
Exception Details:

... and so on
```
and all of this seems a bit scary, please help me.

**Comment by Bastian** [comment]
Can you try to switch from Jackson version 2.10.0.pr3 (which you are using) to version **2.9.3** (which Javacord is using)?

**Comment by burdoto** [comment]
This was never a problem before, I have seen it run with that version.
Based upon how my computer has been acting recently, I would suggest this was some kind of CPU hiccup.
