### ISSUE TITLE
Logging Framework Problem

### ISSUE THREAD

**Issue by burdoto** [Javacord/Javacord#512]
This happened today and I have no clue what it is or why it happened:
```
2019-11-24 07:15:37,911 main WARN org.apache.logging.log4j.spi.AbstractLogger caught java.lang.NullPointerException logging ReusableParameterizedMessage: Creating shard {} of {} java.lang.NullPointerException
	at java.lang.String.contains(String.java:2133)
	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.util.HashMap$KeySpliterator.tryAdvance(HashMap.java:1577)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:449)
	at org.javacord.core.util.logging.PrivacyProtectionLogger.logMessage(PrivacyProtectionLogger.java:44)
	at org.apache.logging.log4j.spi.AbstractLogger.log(AbstractLogger.java:2102)
	at org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2190)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2144)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2127)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2026)
	at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1899)
	at org.apache.logging.log4j.spi.AbstractLogger.debug(AbstractLogger.java:450)
	at org.javacord.core.DiscordApiBuilderDelegateImpl.login(DiscordApiBuilderDelegateImpl.java:155)
	at org.javacord.api.DiscordApiBuilder.login(DiscordApiBuilder.java:36)
	at de.comroid.Cobalton.<clinit>(Cobalton.java:59)

07:15:37.945 [main] ERROR de.comroid.util.ExceptionLogger - cannot log exception to channels [API=Null]
```

**Comment by Bastian** [comment]
Can you please give us the whole error?
This is only the stack trace without the error message.

**Comment by burdoto** [comment]
This is all that got printed out.

**Comment by Vampire** [comment]
Yes and no.
In the `#github_javacord` channel you see the missing line.
@burdoto just like in Discord you have to have a linebreak after the opening three backticks.
anything that follows after the three backticks is interpreted as the language in which to highlight the code.
In this case it doesn't find a language and thus does not highlight, but nevertheless does not output the "language".

From what I see I'd say you either called `org.javacord.core.util.logging.PrivacyProtectionLogger.addPrivateData(null)` or `org.javacord.core.DiscordApiBuilderDelegateImpl#setToken(null)` (which calls the former).
If then log messages are checked for confidential data, the NPE arises.
I'll add a check to not add `null` private data, but as fix with current verison, just do not call one of the above, it is most probably an error anyway.
