### ISSUE TITLE
Failed to send heartbeat or close web socket!

### ISSUE THREAD

**Issue by Sneakometer** [Javacord/Javacord#593]
Hello, i'm using Javacord to send Chat Messages from my Minecraft Server to a Discord Text Channel.
It's working great so far, my only problem is the console gets spammed with exceptions from Javacord.

` [org.javacord.core.util.gateway.DiscordWebSocketAdapter] Failed to send heartbeat or close web socket!
java.lang.IllegalStateException: zip file closed
        at java.util.zip.ZipFile.ensureOpen(ZipFile.java:915) ~[?:?]
        at java.util.zip.ZipFile.getEntry(ZipFile.java:347) ~[?:?]
        at java.util.zip.ZipFile$1.getEntry(ZipFile.java:1121) ~[?:?]
        at java.util.jar.JarFile.getEntry0(JarFile.java:578) ~[?:?]
        at java.util.jar.JarFile.getEntry(JarFile.java:508) ~[?:?]
        at java.util.jar.JarFile.getJarEntry(JarFile.java:470) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:133) ~[patched_1.16.2.jar:git-Paper-"47740f67c"]
        at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:216) ~[patched_1.16.2.jar:git-Paper-"47740f67c"]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[patched_1.16.2.jar:git-Paper-"47740f67c"]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.16.2.jar:git-Paper-"47740f67c"]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
        at org.javacord.core.util.gateway.DiscordWebSocketAdapter.lambda$startHeartbeat$26(DiscordWebSocketAdapter.java:648) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]`

Running javacord-3.0.6-shaded
on openjdk version "11.0.8" 2020-07-14
Debian 10 (buster)

Any Ideas?
Thanks.

**Comment by Vampire** [comment]
Javacord needs a class that is not loaded yet.
So the class is searched in the class loader.
But Bukkit already discarded that class loader.
Is that when you try to disable the plugin or similar?

**Comment by Sneakometer** [comment]
No, it just spams the exception while the server is running.

**Comment by Vampire** [comment]
I cannot guess whose issue that is, whether Bukkits or yours, I could only guess about that.
I can just tell from the Exception, that Javacord needs a class that was not loaded previously, but the class loader is discarded already.
You might set a breakpoint to where the class loader is discarded and check when and why this happens.

**Comment by Sneakometer** [comment]
Ok, apparently this was my fault as it is only happening when reloading Bukkit's plugin loader using the /rl command.
Restarting the entire server fixed the problem for now.
Weirdly though i never had any issue with the reload command with 3rd party libs until now.

Thanks for help.

**Comment by Vampire** [comment]
Your problem is most probably, that you don't wait for the disconnect. You call `disconnect` which happens asynchronously. Then you let Bukkit immediately continue and thus close the class loader. When now a second or whatever later the shutdown progresses and needs to load a new class, the class loader is closed already and you get those errors shown. You can either make sure all classes that might be needed are loaded already, or you wait for the shutdown to complete before you continue and let Bukkit close the class loader.

**Comment by Vampire** [comment]
#598
