### ISSUE TITLE
java.lang.IllegalStateException: Websocket closed before READY packet was received!

### ISSUE THREAD

**Issue by Oydrey** [Javacord/Javacord#652]
Hello,

I'm currently using the version 3.1.1 of javacord. When i  add intent on my DIscordBuidlerApi : 
`DiscordApi api = new DiscordApiBuilder().setToken(args[0]).setIntents(Intent.GUILD_MEMBERS, Intent.GUILD_PRESENCES).login().join();`

I have this error : 

`Exception in thread "main" java.util.concurrent.CompletionException: java.lang.IllegalStateException: Websocket closed before READY packet was received!
	at java.base/java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:412)
	at java.base/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2115)
	at discord_bot.rubis.Main.main(Main.java:32)
Caused by: java.lang.IllegalStateException: Websocket closed before READY packet was received!
	at org.javacord.core.DiscordApiImpl.lambda$new$6(DiscordApiImpl.java:602)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2144)
	at org.javacord.core.util.gateway.DiscordWebSocketAdapter.onDisconnected(DiscordWebSocketAdapter.java:549)
	at com.neovisionaries.ws.client.ListenerManager.callOnDisconnected(ListenerManager.java:223)
	at com.neovisionaries.ws.client.WebSocket.finish(WebSocket.java:3713)
	at com.neovisionaries.ws.client.WebSocket.onThreadsFinished(WebSocket.java:3683)
	at com.neovisionaries.ws.client.WebSocket.onWritingThreadFinished(WebSocket.java:3672)
	at com.neovisionaries.ws.client.WritingThread.notifyFinished(WritingThread.java:539)
	at com.neovisionaries.ws.client.WritingThread.runMain(WritingThread.java:78)
	at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)
`

I regenerate my discord token and add it but it's not working, i'm not sure that it's a problem of authentification. I hadn't this error before I add Intents.

**Comment by Vampire** [comment]
Isn't there any other error before in the logs?
My guess is, that you didn't enable the priviledged intent that you try to use in your bots settings as required.

**Comment by Bastian** [comment]
Like @Vampire said, this is most likely caused by not enabling the privileged intents in the Discord Developer Portal.
See https://javacord.org/wiki/basic-tutorials/gateway-intents.html#privileged-intents

Additionally, your code only sets the two intents and no other. You most likely just want `.setAllIntents()`.

**Comment by Oydrey** [comment]
Thank you, it was in fact the privileged intents in the Discord Developer Portal which i didn't applay, i forgot this step :D
