### ISSUE TITLE
Assertion Error for Large Shards

### ISSUE THREAD

**Issue by AyuAi** [Javacord/Javacord#657]
Related to Issue #538 (I think).

Same code as in #538, except I am catching Assertion Errors. These assertion errors are no longer happening after reconnects, and are simply... happening. I have actually had to create a system that just force restarts the shard on the assertion errors, because otherwise it spams the console with the assertion errors. This leads me to believe it may not be related, but it's the EXACT same origin, which is beautifully upside-down stacktrace because I'm too lazy to flip it:

```
        at java.base/java.lang.Thread.run(Thread.java:832)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at dev.ayu.teabot.TeaBotShard$2.run(TeaBotShard.java:187)
        at dev.ayu.teabot.XpAndHoney.ServerXpAndHoneyHandler.tick(ServerXpAndHoneyHandler.java:1708)
        at java.base/java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.java:425)
        at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807)
        at dev.ayu.teabot.XpAndHoney.ServerXpAndHoneyHandler.lambda$tick$8(ServerXpAndHoneyHandler.java:1713)
        at dev.ayu.teabot.XpAndHoney.ServerXpAndHoneyHandler.canEarnVcXp(ServerXpAndHoneyHandler.java:1615)
        at org.javacord.core.entity.channel.ServerVoiceChannelImpl.getConnectedUsers(ServerVoiceChannelImpl.java:151)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at org.javacord.core.entity.channel.ServerVoiceChannelImpl.lambda$getConnectedUsers$3(ServerVoiceChannelImpl.java:150)
        at java.base/java.util.Optional.orElseThrow(Optional.java:401)
java.lang.AssertionError
```
Which points to https://github.com/Javacord/Javacord/blob/master/javacord-core/src/main/java/org/javacord/core/entity/channel/ServerVoiceChannelImpl.java#L150

The only thing I can think of this being is a user caching issue with larger shards, because this assertion error only throws when the optionals aren't present.

This theory lines up with my next point, which is major instability/eventually inability to start the bot if there are shards larger than 900k users. The instability really starts hitting at around 600k, and accelerates until the shard needs to be split up into smaller shards. As you can imagine, this makes it very unideal to scale, as Discord has recently increased the max cap of servers to well above 600k users, and there are already Discord servers that surpass the number. If a Javacord bot was added to one of them, I am not sure it would survive.

It is important to note that this only applies to when user caching is enabled from what I understand-- however, the user cache is nice to have! I (and possibly other devs) would need to change a lot of code if scaling meant removing user cache forcibly no matter if you were ready or not.

I now currently run 6 shards, with the largest shard having 570k users. I recently had to move to 6 from 4 because the largest shard was reaching an unstable state at 4, and I believe that was somewhere near 650k-700k users.

I have had to increase the number of shards in an effort to decrease the number of users on the largest shard quite a few times now, so I am rather sure that something is problematic with scaling on Javacord with a usercache enabled. I think if someone has the resources to commit to maintaining a scaling usercache, the library should be able to support it, but maybe there are technical difficulties other than resources that I am blindly not considering.

**Comment by AyuAi** [comment]
Oh, also important to note: The assertion errors seem to only be happening on the largest shard, which is also why I think the scalability is a related issue. All of the small shards never get them, but it could be because they have less users and thus are less likely to have issues. Food for thought

**Comment by AyuAi** [comment]
Update: These assertion errors recently happened on a shard of 319k users, so I am no longer positive about my claim of it being large shard issues. However, it may still be more prominent on larger shards, since I do personally notice a lot higher frequencies of it.

**Comment by AyuAi** [comment]
Update: These assertion errors recently happened on a shard of 319k users, so I am no longer positive about my claim of it being large shard issues. However, it may still be more prominent on larger shards, since I do personally notice a lot higher frequencies of it
