### ISSUE TITLE
Couldn't handle packet of type TYPING_START.

### ISSUE THREAD

**Issue by Pdani001** [Javacord/Javacord#668]
I recently started using Javacord (with version 3.1.1), replacing another API that stopped working for some reason, and when I use it, it works, except it gives off this message every time someone writes a messages.

The only intent I use is GUILD_MESSAGES

```
[20:04:28 WARN]: [org.javacord.core.util.gateway.PacketHandler] Couldn't handle packet of type TYPING_START. Please contact the developer! (packet: {"user_id":"242605722288914434","timestamp":1606244664,"member":{"user":{"username":"Pdani001","public_flags":128,"id":"242605722288914434","discriminator":"9711","avatar":"4cf546adbddd86ab377ee0815f68c7c3"},"roles":["726832874065756210","730203152145449011","746056460089163877","764589992910782494"],"premium_since":null,"nick":null,"mute":false,"joined_at":"2020-07-03T20:48:09.903000+00:00","is_pending":false,"hoisted_role":"746056460089163877","deaf":false},"channel_id":"767967463425703937","guild_id":"726828046673379400"})
java.lang.IllegalStateException: zip file closed
        at java.util.zip.ZipFile.ensureOpen(Unknown Source) ~[?:1.8.0_271]
        at java.util.zip.ZipFile.getEntry(Unknown Source) ~[?:1.8.0_271]
        at java.util.jar.JarFile.getEntry(Unknown Source) ~[?:1.8.0_271]
        at java.util.jar.JarFile.getJarEntry(Unknown Source) ~[?:1.8.0_271]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:133) ~[patched_1.16.4.jar:git-Paper-291]
        at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:216) ~[patched_1.16.4.jar:git-Paper-291]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[patched_1.16.4.jar:git-Paper-291]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.16.4.jar:git-Paper-291]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_271]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_271]
        at org.javacord.core.util.handler.user.TypingStartHandler.handle(TypingStartHandler.java:44) ~[?:?]
        at org.javacord.core.util.gateway.PacketHandler.lambda$handlePacket$0(PacketHandler.java:51) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_271]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_271]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_271]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_271]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]
```

**Comment by Bastian** [comment]
This is not a Javacord issue. See https://github.com/Javacord/Javacord/issues/593

**Comment by Pdani001** [comment]
Oops, sorry, didn't notice that. Thanks for the help! :)
