### ISSUE TITLE
Authentication Failure on code that worked perfectly before

### ISSUE THREAD

**Issue by sinsa92** [Javacord/Javacord#671]
Hi! 

I'm having trouble on Bot startup. It says Authentication failed, but I used the token correctly (also tried regenerating). Also, it worked earlier and today (without changing something) it does not anymore.

Using:
I'm using Javacord 3.1.1 on Windows 10, Maven 3.6.3 and Java 1.8.0_241. We're launching the Application with Spring boot.

Expected result:
The bot should login to Discord normally.

Actual Result:
I'm getting an Authentication failure Stacktrace:
`2020-12-08 10:27:56.747  INFO 8888 --- [  WritingThread] o.j.c.u.gateway.DiscordWebSocketAdapter  : Websocket closed with reason 'Authentication failed.' and code AUTHENTICATION_FAILED (4004) by server!
Exception in thread "main" java.util.concurrent.CompletionException: java.lang.IllegalStateException: Websocket closed before READY packet was received!
	at java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:375)
	at java.util.concurrent.CompletableFuture.join(CompletableFuture.java:1934)
	at ch.discordbot.gbot.bot.Bot.init(Bot.java:39)
	at ch.discordbot.gbot.GBotApplication.main(GBotApplication.java:13)
Caused by: java.lang.IllegalStateException: Websocket closed before READY packet was received!
	at org.javacord.core.DiscordApiImpl.lambda$new$6(DiscordApiImpl.java:602)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
	at org.javacord.core.util.gateway.DiscordWebSocketAdapter.onDisconnected(DiscordWebSocketAdapter.java:549)
	at com.neovisionaries.ws.client.ListenerManager.callOnDisconnected(ListenerManager.java:223)
	at com.neovisionaries.ws.client.WebSocket.finish(WebSocket.java:3713)
	at com.neovisionaries.ws.client.WebSocket.onThreadsFinished(WebSocket.java:3683)
	at com.neovisionaries.ws.client.WebSocket.onWritingThreadFinished(WebSocket.java:3672)
	at com.neovisionaries.ws.client.WritingThread.notifyFinished(WritingThread.java:539)
	at com.neovisionaries.ws.client.WritingThread.runMain(WritingThread.java:78)
	at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)`

Steps I tried:
I did use a jar with a version of the program that worked perfectly fine before. I also tried regenerating the token on Discord, but this didn't solve the problem. I've got all Priviledged intents enabled, and the login line looks like this:
`DiscordApi api = new DiscordApiBuilder().setToken(token).setAllIntents().login().join();`
`token` is an argument passed by the command line.

Is there a way on how to fix this or is this an issue on Discord's side?

**Comment by Vampire** [comment]
Discord closes the connection with authentication failed, there is not much Javacord could do about this.
This usually means your token is wrong.
Maybe Discord has issues, but at least there is nothing mentioned on https://discordstatus.com/ yet.
Maybe try again to make sure your token is correct and there are no spaces or whatever.
If it still does not work, I'd recommend contacting Discord support for help.

**Comment by sinsa92** [comment]
I'm sure the Token is correct, I even regenerated it and then copypasted it into the commandline / my IDE. I did it the same way as before, so I'm pretty sure there's no whitespace problem.
Imma try tomorrow again, but I don't think Discord support respond (they never do to me).

**Comment by sinsa92** [comment]
Connection still fails in another Network on another PC, opened a Ticket on the Discord Support.

**Comment by Bastian** [comment]
That's strange.
You could also try it with a newly created bot or try to login with another Discord library to make 100% sure it's not Javacord's fault.
But I agree with Vampire: I don't see how Javacord could cause this. 

I don't think it's the case here but just to be sure: A common mistake is to use the client secret and not the token. Maybe you swapped those two?

**Comment by sinsa92** [comment]
I used for sure the following:
![grafik](https://user-images.githubusercontent.com/36137659/101641316-e5508500-3a31-11eb-8e35-e43b88025bcf.png)

I also wrote to Discord Support, but they responded that they'll pass the Information to their devteam. Since then I haven't heard anything from then. If I get a response, I'll post it here.

**Comment by sinsa92** [comment]
So I tested it with another Bot of mine, that worked. This should mean it's an issue on Discord's side.
I'll close the Issue here since it's not Javacord related, but thanks for the help anyway 😃
