### ISSUE TITLE
AudioConnection breaks when bot is moved by a user

### ISSUE THREAD

**Issue by brona-ruzicka** [Javacord/Javacord#693]
When a user moves the already connected bot to another channel in a server. It immediately moves back to the original channel, stops playing. And after that if a use moves it somewhere else again, it doesn't resist anymore.

At the moment of the first moving aroun it logs this:

```
2021-01-06 21:58:09.031+0100 INFO org.javacord.core.util.gateway.AudioWebSocketAdapter Websocket closed with reason 'Disconnected.' and code DISCONNECTED (4014) by server for AudioConnection (channel: ServerVoiceChannel (id: 784362251188043797, name: super-smort), sessionId: e9632a33c6109e5bdd2b928db4e00fdb, endpoint: eu-central9513.discord.media:443)! {shard=0} 
2021-01-06 21:58:09.441+0100 INFO org.javacord.core.util.gateway.AudioWebSocketAdapter Websocket closed with reason 'Session is no longer valid.' and code SESSION_NO_LONGER_VALID (4006) by server for AudioConnection (channel: ServerVoiceChannel (id: 784362251188043797, name: super-smort), sessionId: e9632a33c6109e5bdd2b928db4e00fdb, endpoint: eu-central9513.discord.media:443)! {shard=0}
```

Also all functions closing or opening a connection in that Server fail and throw this:
```
Exception in thread "main" java.lang.NullPointerException
	at org.javacord.core.util.gateway.AudioWebSocketAdapter.disconnect(AudioWebSocketAdapter.java:305)
	at org.javacord.core.audio.AudioConnectionImpl.close(AudioConnectionImpl.java:358)
	at java.base/java.util.Optional.map(Optional.java:265)
	at org.javacord.core.entity.channel.ServerVoiceChannelImpl.connect(ServerVoiceChannelImpl.java:116)
	at com.brona.firstjavacord.JavacordBot.main(JavacordBot.java:76)
```

What I would expect it to do is just move to the other channel without any reconnecting back. That should be (potentialy) handled by my own code.

**Comment by Vampire** [comment]
It's probably the same bug that it auto-reconnects when being kicked. I don't find the ticket right now, but I think @Mysterypotatoguy was working on a fix.
