### ISSUE TITLE
IllegalStateException: Channel update with unknown role

### ISSUE THREAD

**Issue by AyuAi** [Javacord/Javacord#700]
Heyo, just got a random error in my console that seems to be on Javacord's behalf:
https://i.ayu.dev/img/LfNiYRrIxWA.png

There is no header to the error, and that's the full stacktrace. Unfortunately, that's all the info I have regarding it. Excess memory and CPU were abundant, so it shouldn't be related to such.

**Comment by KILLEliteMaste** [comment]
Since the link does no longer work and I got the same error I will post my stacktrace
```
[WARN ] 2021-03-03 01:51:27 [Javacord - Handlers Processor] PacketHandler - Couldn't handle packet of type CHANNEL_UPDATE. Please contact the developer!(packet: {"type":0,"topic":"Be advised,  this may or may not get daily updates.\n\n(Announcements May or may not be related to Comfort Hotel)","rate_limit_per_user":0,"position":33,"permission_overwrites":[{"type":"role","id":"428077597482549259","deny_new":"7168","deny":7168,"allow_new":"65536","allow":65536},{"type":"role","id":"550029111117217793","deny_new":"2099200","deny":2099200,"allow_new":"0","allow":0},{"type":"role","id":"550029873402347520","deny_new":"5120","deny":5120,"allow_new":"65536","allow":65536},{"type":"role","id":"597714723701522432","deny_new":"1024","deny":1024,"allow_new":"0","allow":0},{"type":"role","id":"621612726334259201","deny_new":"2099200","deny":2099200,"allow_new":"0","allow":0},{"type":"role","id":"675145650379161620","deny_new":"2112","deny":2112,"allow_new":"1024","allow":1024}],"parent_id":"664306115500179506","nsfw":true,"name":"announcements","last_message_id":"735535126968008745","id":"496637176746868736","guild_id":"428077597482549259","guild_hashes":{"version":1,"roles":{"hash":"Ql6xaQv+wNU"},"metadata":{"hash":"ZWFI3gWTfzo"},"channels":{"hash":"Ak7VheAf9jo"}}})
java.lang.IllegalStateException: Received channel update event with unknown role!
        at org.javacord.core.util.handler.channel.ChannelUpdateHandler.lambda$handleServerChannel$0(ChannelUpdateHandle>        at java.util.Optional.orElseThrow(Optional.java:401) ~[?:?]
        at org.javacord.core.util.handler.channel.ChannelUpdateHandler.handleServerChannel(ChannelUpdateHandler.java:17>        at org.javacord.core.util.handler.channel.ChannelUpdateHandler.handle(ChannelUpdateHandler.java:74) ~[javacord->        at org.javacord.core.util.gateway.PacketHandler.lambda$handlePacket$0(PacketHandler.java:51) ~[javacord-core-3.>        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
        at java.lang.Thread.run(Thread.java:832) [?:?]```

**Comment by AyuAi** [comment]
> Since the link does no longer work 

As per your mention (ty btw), I have fixed the image URL. I had recently migrated the location of my image saves but had forgot to move all of my previous ones lol.
