### ISSUE TITLE
Caching not working due to the new channel type

### ISSUE THREAD

**Issue by RedsTom** [Javacord/Javacord#725]
Due to the new "Radio" channel type, if there is a channel created with the Radio type, Javacord will no longer be able to cache the channel and will throw an `AssertionError` in `ServerImpl` at line 379.

```
java.lang.AssertionError: null
	at java.util.Optional.orElseThrow(Optional.java:401) ~[?:?]
	at org.javacord.core.entity.server.ServerImpl.<init>(ServerImpl.java:379) ~[javacord-core-3.1.2.jar:?]
	at org.javacord.core.util.handler.guild.GuildCreateHandler.handle(GuildCreateHandler.java:33) ~[javacord-core-3.1.2.jar:?]
	at org.javacord.core.util.gateway.PacketHandler.lambda$handlePacket$0(PacketHandler.java:51) ~[javacord-core-3.1.2.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
```

**Comment by Bastian** [comment]
As this happens in the constructor, this does probably break the entire bot on the affected server.
I will look into it tomorrow and try to publish a hot-fix asap.
