### ISSUE TITLE
Project not starting on Server

### ISSUE THREAD

**Issue by zVerox** [Javacord/Javacord#735]
Hello,
My Project is not starting on my Server because of this Error:
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: org/javacord/api/listener/message/MessageCreateListener
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
        at java.lang.Class.getMethod0(Class.java:3018)
        at java.lang.Class.getMethod(Class.java:1784)
        at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:650)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:632)
Caused by: java.lang.ClassNotFoundException: org.javacord.api.listener.message.MessageCreateListener
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 7 more
On IntelliJ it starts.

**Comment by Vampire** [comment]
As told on the Discord server, this most likely is because you don't have your dependencies on your class path when you try to start it outside the IDE. Best is you build a proper distribution with Gradle `application` plugin with three lines or a combination of Maven `assembly` and `appassembler` plugin and a load of configuration to achieve the same, or if you want to follow bad practices and easily mess up a fat jar using Gradle `shadow` or Maven `shade` plugin.
