### ISSUE TITLE
NPE on Message Create Packet for News Channel

### ISSUE THREAD

**Issue by ShindouMihou** [Javacord/Javacord#781]
This is on snapshot version 3.3.1 (as of Monday, 6/14/2021)
```
[14 Jun 2021 11:35:16] [Javacord - Handlers Processor] [o.j.core.util.gateway.PacketHandler:WARN ] > Couldn't handle packet of type MESSAGE_CREATE. Please contact the developer! (packet: {"type":12,"tts":false,"timestamp":"2021-06-14T09:35:16.194000+00:00","pinned":false,"message_reference":{"guild_id":"768263169432223745","channel_id":"797215861114404973"},"mentions":[],"mention_roles":[],"mention_everyone":false,"member":{"roles":["853619134821957642","853825275955904532","853825313482342450"],"premium_since":null,"pending":false,"nick":null,"mute":false,"joined_at":"2021-06-13T08:36:11.507000+00:00","is_pending":false,"hoisted_role":"853619134821957642","deaf":false,"avatar":null},"id":"853930582765207582","flags":0,"embeds":[],"edited_timestamp":null,"content":"9Community #announcements","components":[],"channel_id":"REDACTED","author":{"username":"REDACTED","public_flags":0,"id":"REDACTED","discriminator":"0161","avatar":"c8df6996d4f1176085c236c54eb2758e"},"attachments":[],"guild_id":"REDACTED"})
java.lang.NullPointerException: null
        at org.javacord.core.entity.message.MessageImpl.<init>(MessageImpl.java:236)
        at org.javacord.core.DiscordApiImpl.lambda$getOrCreateMessage$29(DiscordApiImpl.java:1105)
        at java.base/java.util.Optional.orElseGet(Optional.java:369)
        at org.javacord.core.DiscordApiImpl.getOrCreateMessage(DiscordApiImpl.java:1105)
        at org.javacord.core.util.handler.message.MessageCreateHandler.handle(MessageCreateHandler.java:66)
        at org.javacord.core.util.handler.message.MessageCreateHandler.handle(MessageCreateHandler.java:59)
        at org.javacord.core.util.gateway.PacketHandler.lambda$handlePacket$0(PacketHandler.java:51)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

Beautified JSON:
```json
{
  "type": 12,
  "tts": false,
  "timestamp": "2021-06-14T09:35:16.194000+00:00",
  "pinned": false,
  "message_reference": {
    "guild_id": "768263169432223745",
    "channel_id": "797215861114404973"
  },
  "mentions": [],
  "mention_roles": [],
  "mention_everyone": false,
  "member": {
    "roles": [
      "853619134821957642",
      "853825275955904532",
      "853825313482342450"
    ],
    "premium_since": null,
    "pending": false,
    "nick": null,
    "mute": false,
    "joined_at": "2021-06-13T08:36:11.507000+00:00",
    "is_pending": false,
    "hoisted_role": "853619134821957642",
    "deaf": false,
    "avatar": null
  },
  "id": "853930582765207582",
  "flags": 0,
  "embeds": [],
  "edited_timestamp": null,
  "content": "REDACTED",
  "components": [],
  "channel_id": "REDACTED",
  "author": {
    "username": "REDACTED",
    "public_flags": 0,
    "id": "REDACTED",
    "discriminator": "0161",
    "avatar": "c8df6996d4f1176085c236c54eb2758e"
  },
  "attachments": [],
  "guild_id": "REDACTED"
}
```

**Comment by Joshix-1** [comment]
3.3.0 is already released.

**Comment by ShindouMihou** [comment]
> 
> 
> 3.3.0 is already released.

Typo, I meant 3.3.1

**Comment by KILLEliteMaste** [comment]
Documentation reference https://discord.com/developers/docs/resources/channel#message-reference-object

**Comment by Joshix-1** [comment]
Is the guild_id the same as the guild_id in the message_reference?

**Comment by ShindouMihou** [comment]
T

> 
> 
> Is the guild_id the same as the guild_id in the message_reference?

(Even though I redacted the data here, it is public on Discord :cough:) Well, the guild_id for the two are different.

**Comment by KILLEliteMaste** [comment]
> Is the guild_id the same as the guild_id in the message_reference?

This depends on the message_reference. For a reply to a message it can(because of DM's) exists while for crossposted messages it's from the message originated guild

**Comment by Joshix-1** [comment]
If I remember correctly Javacord assumes that the guild_ids are the same
