### ISSUE TITLE
Couldn't handle packet of type INTERACTION_CREATE

### ISSUE THREAD

**Issue by Bastian** [Javacord/Javacord#795]
```
2021-06-30 21:27:11.979+0200 WARN org.javacord.core.util.gateway.PacketHandler Couldn't handle packet of type INTERACTION_CREATE. Please contact the developer! (packet: {"version":1,"type":3,"token":"<redacted>","message":{"id":"859877451131256832","flags":64},"member":{"user":{"username":"Bastian","public_flags":768,"id":"157862224206102529","discriminator":"0310","avatar":"b69de4679e4ee28c5235e75a6eca4aa3"},"roles":["151325992038825984"],"premium_since":null,"permissions":"137438953471","pending":false,"nick":"Bastian","mute":false,"joined_at":"2016-03-11T15:31:25.546000+00:00","is_pending":false,"deaf":false,"avatar":null},"id":"859877752002052116","guild_id":"151037561152733184","data":{"custom_id":"success","component_type":2},"channel_id":"151326329839681536","application_id":"157889000391180288"}) {shard=0} 
 java.lang.AssertionError
	at java.util.Optional.orElseThrow(Optional.java:290)
	at org.javacord.core.interaction.InteractionImpl.<init>(InteractionImpl.java:60)
	at org.javacord.core.interaction.MessageComponentInteractionImpl.<init>(MessageComponentInteractionImpl.java:37)
	at org.javacord.core.interaction.ButtonInteractionImpl.<init>(ButtonInteractionImpl.java:18)
	at org.javacord.core.util.handler.interaction.InteractionCreateHandler.handle(InteractionCreateHandler.java:61)
	at org.javacord.core.util.gateway.PacketHandler.lambda$handlePacket$0(PacketHandler.java:51)
```

This happened when clicking on a button that was created with the following code:
```java
SlashCommand.with("example", "An example command").createForServer(api.getServerById(151037561152733184L).get()).join();

api.addSlashCommandCreateListener(event -> {
    SlashCommandInteraction slashCommandInteraction = event.getSlashCommandInteraction();
    if (slashCommandInteraction.getCommandName().equals("example")) {
        slashCommandInteraction.createImmediateResponder()
            .setContent("Slash commands are cool!")
            .setFlags(MessageFlag.EPHEMERAL)
            .addComponents(
                ActionRow.of(Button.success("success", "And"),
                    Button.danger("danger", "buttons"),
                    Button.secondary("secondary", "are too!")))
            .respond();
    }
});
```

**Comment by puttydotexe** [comment]
Temporary workaround is removing the `EPHEMERAL` flag from the `setFlags#` constructor.

**Comment by KILLEliteMaste** [comment]
@Bastian This error is pretty weird, any idea what it could be?
https://github.com/Javacord/Javacord/blob/7a560073eb4f92b334cd5d2a4baf044b451e929f/javacord-core/src/main/java/org/javacord/core/util/handler/interaction/InteractionCreateHandler.java#L41-L45

When you first invoke the command everything work like a charm and the channel_id is from the server text channel this command was invoked from. Therefore the channel is of type `SERVER_TEXT_CHANNEL`. When you next click on the button(to get the exception) the channel id is again the same from the server text channel **BUT** this time if you call channel#getType it is from type `PRIVATE_CHANNEL`. Sending a message to both interaction (slash command / the button event) below the code snipped results in sending the message to the correct server text channel in the sever.

**Comment by KILLEliteMaste** [comment]
Nevermind. 
The issue is Discord sends ephemeral messages in the same format as messages in DM's. This results in a missing `guild_id` and therefore we create a private channel as we currently assume messages without a `guild_id` is a DM.
